/*
 * Inventory API
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.annotations.SerializedName;



import java.util.Objects;

/**
 * This type is used to provide detailed information about an inventory item.
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-02T16:14:13.966768200+02:00[Europe/Berlin]")
public class InventoryItem {
  public static final String SERIALIZED_NAME_AVAILABILITY = "availability";
  @SerializedName(SERIALIZED_NAME_AVAILABILITY)
  private Availability availability;

  public static final String SERIALIZED_NAME_CONDITION = "condition";
  @SerializedName(SERIALIZED_NAME_CONDITION)
  private String condition;

  public static final String SERIALIZED_NAME_CONDITION_DESCRIPTION = "conditionDescription";
  @SerializedName(SERIALIZED_NAME_CONDITION_DESCRIPTION)
  private String conditionDescription;

  public static final String SERIALIZED_NAME_PACKAGE_WEIGHT_AND_SIZE = "packageWeightAndSize";
  @SerializedName(SERIALIZED_NAME_PACKAGE_WEIGHT_AND_SIZE)
  private PackageWeightAndSize packageWeightAndSize;

  public static final String SERIALIZED_NAME_PRODUCT = "product";
  @SerializedName(SERIALIZED_NAME_PRODUCT)
  private Product product;


  public InventoryItem availability(Availability availability) {
    
    this.availability = availability;
    return this;
  }

   /**
   * Get availability
   * @return availability
  **/
  


  public Availability getAvailability() {
    return availability;
  }


  public void setAvailability(Availability availability) {
    this.availability = availability;
  }


  public InventoryItem condition(String condition) {
    
    this.condition = condition;
    return this;
  }

   /**
   * This enumeration value indicates the condition of the item. Supported item condition values will vary by eBay site and category. To see which item condition values that a particular eBay category supports, use the &lt;a href&#x3D;\&quot;/api-docs/sell/metadata/resources/marketplace/methods/getItemConditionPolicies\&quot;&gt;getItemConditionPolicies&lt;/a&gt; method of the &lt;strong&gt;Metadata API&lt;/strong&gt;. This method returns condition ID values that map to the enumeration values defined in the &lt;a href&#x3D;\&quot;/api-docs/sell/inventory/types/slr:ConditionEnum\&quot;&gt;ConditionEnum&lt;/a&gt; type. The &lt;a href&#x3D;\&quot;/api-docs/sell/static/metadata/condition-id-values.html\&quot;&gt;Item condition ID and name values&lt;/a&gt; topic in the &lt;strong&gt;Selling Integration Guide&lt;/strong&gt; has a table that maps condition ID values to &lt;strong&gt;ConditionEnum&lt;/strong&gt; values. The &lt;strong&gt;getItemConditionPolicies&lt;/strong&gt; call reference page has more information.&lt;br&gt;&lt;br&gt; A &lt;strong&gt;condition&lt;/strong&gt; value is optional up until the seller is ready to publish an offer with the SKU, at which time it becomes required for most eBay categories. For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/inventory/types/slr:ConditionEnum&#39;&gt;eBay API documentation&lt;/a&gt;
   * @return condition
  **/
  


  public String getCondition() {
    return condition;
  }


  public void setCondition(String condition) {
    this.condition = condition;
  }


  public InventoryItem conditionDescription(String conditionDescription) {
    
    this.conditionDescription = conditionDescription;
    return this;
  }

   /**
   * This string field is used by the seller to more clearly describe the condition of a used inventory item, or an inventory item whose &lt;strong&gt;condition&lt;/strong&gt; value is not &lt;code&gt;NEW&lt;/code&gt;, &lt;code&gt;LIKE_NEW&lt;/code&gt;, &lt;code&gt;NEW_OTHER&lt;/code&gt;, or &lt;code&gt;NEW_WITH_DEFECTS&lt;/code&gt;.&lt;br/&gt;&lt;br/&gt; The &lt;strong&gt;conditionDescription&lt;/strong&gt; field is available for all eBay categories. If the &lt;strong&gt;conditionDescription&lt;/strong&gt; field is used with an item in one of the new conditions (mentioned in previous paragraph), eBay will simply ignore this field if included, and eBay will return a warning message to the user. &lt;br/&gt;&lt;br/&gt; This field should only be used to further clarify the condition of the used item. It should not be used for branding, promotions, shipping, returns, payment or other information unrelated to the condition of the used item. Make sure that the &lt;strong&gt;condition&lt;/strong&gt; value, condition description, listing description, and the item&#39;s pictures do not contradict one another. &lt;br /&gt;&lt;br /&gt; This field is not always required, but is required if an inventory item is being updated and a condition description already exists for that inventory item. &lt;br /&gt;&lt;br /&gt; This field is returned in the &lt;strong&gt;getInventoryItem&lt;/strong&gt; and &lt;strong&gt;getInventoryItems&lt;/strong&gt; calls if a condition description was provided for a used inventory item.&lt;br/&gt;&lt;br/&gt;&lt;strong&gt;Max Length&lt;/strong&gt;: 1000.
   * @return conditionDescription
  **/
  


  public String getConditionDescription() {
    return conditionDescription;
  }


  public void setConditionDescription(String conditionDescription) {
    this.conditionDescription = conditionDescription;
  }


  public InventoryItem packageWeightAndSize(PackageWeightAndSize packageWeightAndSize) {
    
    this.packageWeightAndSize = packageWeightAndSize;
    return this;
  }

   /**
   * Get packageWeightAndSize
   * @return packageWeightAndSize
  **/
  


  public PackageWeightAndSize getPackageWeightAndSize() {
    return packageWeightAndSize;
  }


  public void setPackageWeightAndSize(PackageWeightAndSize packageWeightAndSize) {
    this.packageWeightAndSize = packageWeightAndSize;
  }


  public InventoryItem product(Product product) {
    
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  


  public Product getProduct() {
    return product;
  }


  public void setProduct(Product product) {
    this.product = product;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventoryItem inventoryItem = (InventoryItem) o;
    return Objects.equals(this.availability, inventoryItem.availability) &&
        Objects.equals(this.condition, inventoryItem.condition) &&
        Objects.equals(this.conditionDescription, inventoryItem.conditionDescription) &&
        Objects.equals(this.packageWeightAndSize, inventoryItem.packageWeightAndSize) &&
        Objects.equals(this.product, inventoryItem.product);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availability, condition, conditionDescription, packageWeightAndSize, product);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryItem {\n");
    sb.append("    availability: ").append(toIndentedString(availability)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    conditionDescription: ").append(toIndentedString(conditionDescription)).append("\n");
    sb.append("    packageWeightAndSize: ").append(toIndentedString(packageWeightAndSize)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

