/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.magento.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;


import java.util.ArrayList;
import java.util.List;

/**
 * Interface RmaInterface
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class RmaDataRmaInterface {
  public static final String SERIALIZED_NAME_INCREMENT_ID = "increment_id";
  @SerializedName(SERIALIZED_NAME_INCREMENT_ID)
  private String incrementId;

  public static final String SERIALIZED_NAME_ENTITY_ID = "entity_id";
  @SerializedName(SERIALIZED_NAME_ENTITY_ID)
  private Integer entityId;

  public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
  @SerializedName(SERIALIZED_NAME_ORDER_ID)
  private Integer orderId;

  public static final String SERIALIZED_NAME_ORDER_INCREMENT_ID = "order_increment_id";
  @SerializedName(SERIALIZED_NAME_ORDER_INCREMENT_ID)
  private String orderIncrementId;

  public static final String SERIALIZED_NAME_STORE_ID = "store_id";
  @SerializedName(SERIALIZED_NAME_STORE_ID)
  private Integer storeId;

  public static final String SERIALIZED_NAME_CUSTOMER_ID = "customer_id";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_ID)
  private Integer customerId;

  public static final String SERIALIZED_NAME_DATE_REQUESTED = "date_requested";
  @SerializedName(SERIALIZED_NAME_DATE_REQUESTED)
  private String dateRequested;

  public static final String SERIALIZED_NAME_CUSTOMER_CUSTOM_EMAIL = "customer_custom_email";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_CUSTOM_EMAIL)
  private String customerCustomEmail;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<RmaDataItemInterface> items = new ArrayList<RmaDataItemInterface>();

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  private List<RmaDataCommentInterface> comments = new ArrayList<RmaDataCommentInterface>();

  public static final String SERIALIZED_NAME_TRACKS = "tracks";
  @SerializedName(SERIALIZED_NAME_TRACKS)
  private List<RmaDataTrackInterface> tracks = new ArrayList<RmaDataTrackInterface>();

  public static final String SERIALIZED_NAME_EXTENSION_ATTRIBUTES = "extension_attributes";
  @SerializedName(SERIALIZED_NAME_EXTENSION_ATTRIBUTES)
  private Object extensionAttributes;

  public static final String SERIALIZED_NAME_CUSTOM_ATTRIBUTES = "custom_attributes";
  @SerializedName(SERIALIZED_NAME_CUSTOM_ATTRIBUTES)
  private List<FrameworkAttributeInterface> customAttributes = null;


  public RmaDataRmaInterface incrementId(String incrementId) {
    
    this.incrementId = incrementId;
    return this;
  }

   /**
   * Entity_id
   * @return incrementId
  **/
  

  public String getIncrementId() {
    return incrementId;
  }


  public void setIncrementId(String incrementId) {
    this.incrementId = incrementId;
  }


  public RmaDataRmaInterface entityId(Integer entityId) {
    
    this.entityId = entityId;
    return this;
  }

   /**
   * Entity_id
   * @return entityId
  **/
  

  public Integer getEntityId() {
    return entityId;
  }


  public void setEntityId(Integer entityId) {
    this.entityId = entityId;
  }


  public RmaDataRmaInterface orderId(Integer orderId) {
    
    this.orderId = orderId;
    return this;
  }

   /**
   * Order_id
   * @return orderId
  **/
  

  public Integer getOrderId() {
    return orderId;
  }


  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }


  public RmaDataRmaInterface orderIncrementId(String orderIncrementId) {
    
    this.orderIncrementId = orderIncrementId;
    return this;
  }

   /**
   * Order_increment_id
   * @return orderIncrementId
  **/
  

  public String getOrderIncrementId() {
    return orderIncrementId;
  }


  public void setOrderIncrementId(String orderIncrementId) {
    this.orderIncrementId = orderIncrementId;
  }


  public RmaDataRmaInterface storeId(Integer storeId) {
    
    this.storeId = storeId;
    return this;
  }

   /**
   * Store_id
   * @return storeId
  **/
  

  public Integer getStoreId() {
    return storeId;
  }


  public void setStoreId(Integer storeId) {
    this.storeId = storeId;
  }


  public RmaDataRmaInterface customerId(Integer customerId) {
    
    this.customerId = customerId;
    return this;
  }

   /**
   * Customer_id
   * @return customerId
  **/
  

  public Integer getCustomerId() {
    return customerId;
  }


  public void setCustomerId(Integer customerId) {
    this.customerId = customerId;
  }


  public RmaDataRmaInterface dateRequested(String dateRequested) {
    
    this.dateRequested = dateRequested;
    return this;
  }

   /**
   * Date_requested
   * @return dateRequested
  **/
  

  public String getDateRequested() {
    return dateRequested;
  }


  public void setDateRequested(String dateRequested) {
    this.dateRequested = dateRequested;
  }


  public RmaDataRmaInterface customerCustomEmail(String customerCustomEmail) {
    
    this.customerCustomEmail = customerCustomEmail;
    return this;
  }

   /**
   * Customer_custom_email
   * @return customerCustomEmail
  **/
  

  public String getCustomerCustomEmail() {
    return customerCustomEmail;
  }


  public void setCustomerCustomEmail(String customerCustomEmail) {
    this.customerCustomEmail = customerCustomEmail;
  }


  public RmaDataRmaInterface items(List<RmaDataItemInterface> items) {
    
    this.items = items;
    return this;
  }

  public RmaDataRmaInterface addItemsItem(RmaDataItemInterface itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Items
   * @return items
  **/
  

  public List<RmaDataItemInterface> getItems() {
    return items;
  }


  public void setItems(List<RmaDataItemInterface> items) {
    this.items = items;
  }


  public RmaDataRmaInterface status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Status
   * @return status
  **/
  

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public RmaDataRmaInterface comments(List<RmaDataCommentInterface> comments) {
    
    this.comments = comments;
    return this;
  }

  public RmaDataRmaInterface addCommentsItem(RmaDataCommentInterface commentsItem) {
    this.comments.add(commentsItem);
    return this;
  }

   /**
   * Comments list
   * @return comments
  **/
  

  public List<RmaDataCommentInterface> getComments() {
    return comments;
  }


  public void setComments(List<RmaDataCommentInterface> comments) {
    this.comments = comments;
  }


  public RmaDataRmaInterface tracks(List<RmaDataTrackInterface> tracks) {
    
    this.tracks = tracks;
    return this;
  }

  public RmaDataRmaInterface addTracksItem(RmaDataTrackInterface tracksItem) {
    this.tracks.add(tracksItem);
    return this;
  }

   /**
   * Tracks list
   * @return tracks
  **/
  

  public List<RmaDataTrackInterface> getTracks() {
    return tracks;
  }


  public void setTracks(List<RmaDataTrackInterface> tracks) {
    this.tracks = tracks;
  }


  public RmaDataRmaInterface extensionAttributes(Object extensionAttributes) {
    
    this.extensionAttributes = extensionAttributes;
    return this;
  }

   /**
   * ExtensionInterface class for @see \\Magento\\Rma\\Api\\Data\\RmaInterface
   * @return extensionAttributes
  **/
  
  

  public Object getExtensionAttributes() {
    return extensionAttributes;
  }


  public void setExtensionAttributes(Object extensionAttributes) {
    this.extensionAttributes = extensionAttributes;
  }


  public RmaDataRmaInterface customAttributes(List<FrameworkAttributeInterface> customAttributes) {
    
    this.customAttributes = customAttributes;
    return this;
  }

  public RmaDataRmaInterface addCustomAttributesItem(FrameworkAttributeInterface customAttributesItem) {
    if (this.customAttributes == null) {
      this.customAttributes = new ArrayList<FrameworkAttributeInterface>();
    }
    this.customAttributes.add(customAttributesItem);
    return this;
  }

   /**
   * Custom attributes values.
   * @return customAttributes
  **/
  
  

  public List<FrameworkAttributeInterface> getCustomAttributes() {
    return customAttributes;
  }


  public void setCustomAttributes(List<FrameworkAttributeInterface> customAttributes) {
    this.customAttributes = customAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RmaDataRmaInterface rmaDataRmaInterface = (RmaDataRmaInterface) o;
    return Objects.equals(this.incrementId, rmaDataRmaInterface.incrementId) &&
        Objects.equals(this.entityId, rmaDataRmaInterface.entityId) &&
        Objects.equals(this.orderId, rmaDataRmaInterface.orderId) &&
        Objects.equals(this.orderIncrementId, rmaDataRmaInterface.orderIncrementId) &&
        Objects.equals(this.storeId, rmaDataRmaInterface.storeId) &&
        Objects.equals(this.customerId, rmaDataRmaInterface.customerId) &&
        Objects.equals(this.dateRequested, rmaDataRmaInterface.dateRequested) &&
        Objects.equals(this.customerCustomEmail, rmaDataRmaInterface.customerCustomEmail) &&
        Objects.equals(this.items, rmaDataRmaInterface.items) &&
        Objects.equals(this.status, rmaDataRmaInterface.status) &&
        Objects.equals(this.comments, rmaDataRmaInterface.comments) &&
        Objects.equals(this.tracks, rmaDataRmaInterface.tracks) &&
        Objects.equals(this.extensionAttributes, rmaDataRmaInterface.extensionAttributes) &&
        Objects.equals(this.customAttributes, rmaDataRmaInterface.customAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(incrementId, entityId, orderId, orderIncrementId, storeId, customerId, dateRequested, customerCustomEmail, items, status, comments, tracks, extensionAttributes, customAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RmaDataRmaInterface {\n");
    sb.append("    incrementId: ").append(toIndentedString(incrementId)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    orderIncrementId: ").append(toIndentedString(orderIncrementId)).append("\n");
    sb.append("    storeId: ").append(toIndentedString(storeId)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    dateRequested: ").append(toIndentedString(dateRequested)).append("\n");
    sb.append("    customerCustomEmail: ").append(toIndentedString(customerCustomEmail)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    tracks: ").append(toIndentedString(tracks)).append("\n");
    sb.append("    extensionAttributes: ").append(toIndentedString(extensionAttributes)).append("\n");
    sb.append("    customAttributes: ").append(toIndentedString(customAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

