/**
* Inventory API
* The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
*
* The version of the OpenAPI document: 1.16.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package de.daill.model.ebay

import com.squareup.moshi.Json

/**
 * This type is used by the base response payload for the <strong>getInventoryLocations</strong> call.
 * @param href The URI of the current page of results from the result set.
 * @param limit The number of items returned on a single page from the result set.
 * @param next The URI for the following page of results. This value is returned only if there is an additional page of results to display from the result set. <br><br><b>Max length</b>: 2048
 * @param offset The number of results skipped in the result set before listing the first returned result. This value is set in the request with the <b>offset</b> query parameter. <p class=\"tablenote\"><strong>Note: </strong>The items in a paginated result set use a zero-based list where the first item in the list has an offset of <code>0</code>.</p>
 * @param prev The URI for the preceding page of results. This value is returned only if there is a previous page of results to display from the result set. <br><br><b>Max length</b>: 2048
 * @param total The total number of items retrieved in the result set.  <br><br>If no items are found, this field is returned with a value of <code>0</code>.
 * @param locations An array of one or more of the merchant's inventory locations.
 */

data class LocationResponse (
    /* The URI of the current page of results from the result set. */
    @Json(name = "href")
    val href: kotlin.String? = null,
    /* The number of items returned on a single page from the result set. */
    @Json(name = "limit")
    val limit: kotlin.Int? = null,
    /* The URI for the following page of results. This value is returned only if there is an additional page of results to display from the result set. <br><br><b>Max length</b>: 2048 */
    @Json(name = "next")
    val next: kotlin.String? = null,
    /* The number of results skipped in the result set before listing the first returned result. This value is set in the request with the <b>offset</b> query parameter. <p class=\"tablenote\"><strong>Note: </strong>The items in a paginated result set use a zero-based list where the first item in the list has an offset of <code>0</code>.</p> */
    @Json(name = "offset")
    val offset: kotlin.Int? = null,
    /* The URI for the preceding page of results. This value is returned only if there is a previous page of results to display from the result set. <br><br><b>Max length</b>: 2048 */
    @Json(name = "prev")
    val prev: kotlin.String? = null,
    /* The total number of items retrieved in the result set.  <br><br>If no items are found, this field is returned with a value of <code>0</code>. */
    @Json(name = "total")
    val total: kotlin.Int? = null,
    /* An array of one or more of the merchant's inventory locations. */
    @Json(name = "locations")
    val locations: kotlin.collections.List<InventoryLocationResponse>? = null
)

