/**
* Inventory API
* The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
*
* The version of the OpenAPI document: 1.16.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package de.daill.ebay.models

import com.squareup.moshi.Json

/**
 * This type is used by the <b>createInventoryLocation</b> call to provide an full or partial address of an inventory location.
 * @param address 
 * @param geoCoordinates 
 */

data class LocationDetails (
    @Json(name = "address")
    val address: de.daill.ebay.models.Address? = null,
    @Json(name = "geoCoordinates")
    val geoCoordinates: de.daill.ebay.models.GeoCoordinates? = null
)

