/**
* Inventory API
* The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
*
* The version of the OpenAPI document: 1.16.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package de.daill.ebay.models


import com.squareup.moshi.Json

/**
 * This type is used to specify the details of a motor vehicle that is compatible with the inventory item specified through the SKU value in the call URI.
 * @param engine This field indicates the specifications of the engine, including its size, block type, and fuel type. An example is <code>2.7L V6 gas DOHC naturally aspirated</code>. This field is conditionally required, but should be supplied if known/applicable.
 * @param make This field indicates the make of the vehicle (e.g. <code>Toyota</code>). This field is always required to identify a motor vehicle.
 * @param model This field indicates the model of the vehicle (e.g. <code>Camry</code>). This field is always required to identify a motor vehicle.
 * @param trim This field indicates the trim of the vehicle (e.g. <code>2-door Coupe</code>). This field is conditionally required, but should be supplied if known/applicable.
 * @param year This field indicates the year of the vehicle (e.g. <code>2016</code>). This field is always required to identify a motor vehicle.
 */

data class ProductFamilyProperties (
    /* This field indicates the specifications of the engine, including its size, block type, and fuel type. An example is <code>2.7L V6 gas DOHC naturally aspirated</code>. This field is conditionally required, but should be supplied if known/applicable. */
    @Json(name = "engine")
    val engine: kotlin.String? = null,
    /* This field indicates the make of the vehicle (e.g. <code>Toyota</code>). This field is always required to identify a motor vehicle. */
    @Json(name = "make")
    val make: kotlin.String? = null,
    /* This field indicates the model of the vehicle (e.g. <code>Camry</code>). This field is always required to identify a motor vehicle. */
    @Json(name = "model")
    val model: kotlin.String? = null,
    /* This field indicates the trim of the vehicle (e.g. <code>2-door Coupe</code>). This field is conditionally required, but should be supplied if known/applicable. */
    @Json(name = "trim")
    val trim: kotlin.String? = null,
    /* This field indicates the year of the vehicle (e.g. <code>2016</code>). This field is always required to identify a motor vehicle. */
    @Json(name = "year")
    val year: kotlin.String? = null
)

