/**
* Inventory API
* The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
*
* The version of the OpenAPI document: 1.16.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package de.daill.ebay.models

import com.squareup.moshi.Json

/**
 * The base response of the <strong>withdrawOffer</strong> call.
 * @param listingId The unique identifier of the eBay listing associated with the offer that was withdrawn. This field will not be returned if the eBay listing was not successfully ended.
 * @param warnings This container will be returned if there were one or more warnings associated with the attempt to withdraw the offer.
 */

data class WithdrawResponse (
    /* The unique identifier of the eBay listing associated with the offer that was withdrawn. This field will not be returned if the eBay listing was not successfully ended. */
    @Json(name = "listingId")
    val listingId: kotlin.String? = null,
    /* This container will be returned if there were one or more warnings associated with the attempt to withdraw the offer. */
    @Json(name = "warnings")
    val warnings: kotlin.collections.List<de.daill.ebay.models.Error>? = null
)

