/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Interface LinkInterface
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class BundleDataLinkInterface {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  private String sku;

  public static final String SERIALIZED_NAME_OPTION_ID = "option_id";
  @SerializedName(SERIALIZED_NAME_OPTION_ID)
  private Integer optionId;

  public static final String SERIALIZED_NAME_QTY = "qty";
  @SerializedName(SERIALIZED_NAME_QTY)
  private BigDecimal qty;

  public static final String SERIALIZED_NAME_POSITION = "position";
  @SerializedName(SERIALIZED_NAME_POSITION)
  private Integer position;

  public static final String SERIALIZED_NAME_IS_DEFAULT = "is_default";
  @SerializedName(SERIALIZED_NAME_IS_DEFAULT)
  private Boolean isDefault;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private BigDecimal price;

  public static final String SERIALIZED_NAME_PRICE_TYPE = "price_type";
  @SerializedName(SERIALIZED_NAME_PRICE_TYPE)
  private Integer priceType;

  public static final String SERIALIZED_NAME_CAN_CHANGE_QUANTITY = "can_change_quantity";
  @SerializedName(SERIALIZED_NAME_CAN_CHANGE_QUANTITY)
  private Integer canChangeQuantity;

  public static final String SERIALIZED_NAME_EXTENSION_ATTRIBUTES = "extension_attributes";
  @SerializedName(SERIALIZED_NAME_EXTENSION_ATTRIBUTES)
  private Object extensionAttributes;


  public BundleDataLinkInterface id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * The identifier
   * @return id
  **/



  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public BundleDataLinkInterface sku(String sku) {
    
    this.sku = sku;
    return this;
  }

   /**
   * Linked product sku
   * @return sku
  **/



  public String getSku() {
    return sku;
  }


  public void setSku(String sku) {
    this.sku = sku;
  }


  public BundleDataLinkInterface optionId(Integer optionId) {
    
    this.optionId = optionId;
    return this;
  }

   /**
   * Option id
   * @return optionId
  **/



  public Integer getOptionId() {
    return optionId;
  }


  public void setOptionId(Integer optionId) {
    this.optionId = optionId;
  }


  public BundleDataLinkInterface qty(BigDecimal qty) {
    
    this.qty = qty;
    return this;
  }

   /**
   * Qty
   * @return qty
  **/



  public BigDecimal getQty() {
    return qty;
  }


  public void setQty(BigDecimal qty) {
    this.qty = qty;
  }


  public BundleDataLinkInterface position(Integer position) {
    
    this.position = position;
    return this;
  }

   /**
   * Position
   * @return position
  **/



  public Integer getPosition() {
    return position;
  }


  public void setPosition(Integer position) {
    this.position = position;
  }


  public BundleDataLinkInterface isDefault(Boolean isDefault) {
    
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Is default
   * @return isDefault
  **/


  public Boolean getIsDefault() {
    return isDefault;
  }


  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }


  public BundleDataLinkInterface price(BigDecimal price) {
    
    this.price = price;
    return this;
  }

   /**
   * Price
   * @return price
  **/


  public BigDecimal getPrice() {
    return price;
  }


  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  public BundleDataLinkInterface priceType(Integer priceType) {
    
    this.priceType = priceType;
    return this;
  }

   /**
   * Price type
   * @return priceType
  **/


  public Integer getPriceType() {
    return priceType;
  }


  public void setPriceType(Integer priceType) {
    this.priceType = priceType;
  }


  public BundleDataLinkInterface canChangeQuantity(Integer canChangeQuantity) {
    
    this.canChangeQuantity = canChangeQuantity;
    return this;
  }

   /**
   * Whether quantity could be changed
   * @return canChangeQuantity
  **/



  public Integer getCanChangeQuantity() {
    return canChangeQuantity;
  }


  public void setCanChangeQuantity(Integer canChangeQuantity) {
    this.canChangeQuantity = canChangeQuantity;
  }


  public BundleDataLinkInterface extensionAttributes(Object extensionAttributes) {
    
    this.extensionAttributes = extensionAttributes;
    return this;
  }

   /**
   * ExtensionInterface class for @see \\Magento\\Bundle\\Api\\Data\\LinkInterface
   * @return extensionAttributes
  **/



  public Object getExtensionAttributes() {
    return extensionAttributes;
  }


  public void setExtensionAttributes(Object extensionAttributes) {
    this.extensionAttributes = extensionAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BundleDataLinkInterface bundleDataLinkInterface = (BundleDataLinkInterface) o;
    return Objects.equals(this.id, bundleDataLinkInterface.id) &&
        Objects.equals(this.sku, bundleDataLinkInterface.sku) &&
        Objects.equals(this.optionId, bundleDataLinkInterface.optionId) &&
        Objects.equals(this.qty, bundleDataLinkInterface.qty) &&
        Objects.equals(this.position, bundleDataLinkInterface.position) &&
        Objects.equals(this.isDefault, bundleDataLinkInterface.isDefault) &&
        Objects.equals(this.price, bundleDataLinkInterface.price) &&
        Objects.equals(this.priceType, bundleDataLinkInterface.priceType) &&
        Objects.equals(this.canChangeQuantity, bundleDataLinkInterface.canChangeQuantity) &&
        Objects.equals(this.extensionAttributes, bundleDataLinkInterface.extensionAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sku, optionId, qty, position, isDefault, price, priceType, canChangeQuantity, extensionAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BundleDataLinkInterface {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    optionId: ").append(toIndentedString(optionId)).append("\n");
    sb.append("    qty: ").append(toIndentedString(qty)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceType: ").append(toIndentedString(priceType)).append("\n");
    sb.append("    canChangeQuantity: ").append(toIndentedString(canChangeQuantity)).append("\n");
    sb.append("    extensionAttributes: ").append(toIndentedString(extensionAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

