/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;


import java.math.BigDecimal;

/**
 * Tier price interface.
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class CatalogDataTierPriceInterface {
  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private BigDecimal price;

  public static final String SERIALIZED_NAME_PRICE_TYPE = "price_type";
  @SerializedName(SERIALIZED_NAME_PRICE_TYPE)
  private String priceType;

  public static final String SERIALIZED_NAME_WEBSITE_ID = "website_id";
  @SerializedName(SERIALIZED_NAME_WEBSITE_ID)
  private Integer websiteId;

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  private String sku;

  public static final String SERIALIZED_NAME_CUSTOMER_GROUP = "customer_group";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_GROUP)
  private String customerGroup;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private BigDecimal quantity;

  public static final String SERIALIZED_NAME_EXTENSION_ATTRIBUTES = "extension_attributes";
  @SerializedName(SERIALIZED_NAME_EXTENSION_ATTRIBUTES)
  private Object extensionAttributes;


  public CatalogDataTierPriceInterface price(BigDecimal price) {
    
    this.price = price;
    return this;
  }

   /**
   * Tier price.
   * @return price
  **/


  public BigDecimal getPrice() {
    return price;
  }


  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  public CatalogDataTierPriceInterface priceType(String priceType) {
    
    this.priceType = priceType;
    return this;
  }

   /**
   * Tier price type.
   * @return priceType
  **/


  public String getPriceType() {
    return priceType;
  }


  public void setPriceType(String priceType) {
    this.priceType = priceType;
  }


  public CatalogDataTierPriceInterface websiteId(Integer websiteId) {
    
    this.websiteId = websiteId;
    return this;
  }

   /**
   * Website id.
   * @return websiteId
  **/


  public Integer getWebsiteId() {
    return websiteId;
  }


  public void setWebsiteId(Integer websiteId) {
    this.websiteId = websiteId;
  }


  public CatalogDataTierPriceInterface sku(String sku) {
    
    this.sku = sku;
    return this;
  }

   /**
   * SKU.
   * @return sku
  **/


  public String getSku() {
    return sku;
  }


  public void setSku(String sku) {
    this.sku = sku;
  }


  public CatalogDataTierPriceInterface customerGroup(String customerGroup) {
    
    this.customerGroup = customerGroup;
    return this;
  }

   /**
   * Customer group.
   * @return customerGroup
  **/


  public String getCustomerGroup() {
    return customerGroup;
  }


  public void setCustomerGroup(String customerGroup) {
    this.customerGroup = customerGroup;
  }


  public CatalogDataTierPriceInterface quantity(BigDecimal quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * Quantity.
   * @return quantity
  **/


  public BigDecimal getQuantity() {
    return quantity;
  }


  public void setQuantity(BigDecimal quantity) {
    this.quantity = quantity;
  }


  public CatalogDataTierPriceInterface extensionAttributes(Object extensionAttributes) {
    
    this.extensionAttributes = extensionAttributes;
    return this;
  }

   /**
   * ExtensionInterface class for @see \\Magento\\Catalog\\Api\\Data\\TierPriceInterface
   * @return extensionAttributes
  **/

  

  public Object getExtensionAttributes() {
    return extensionAttributes;
  }


  public void setExtensionAttributes(Object extensionAttributes) {
    this.extensionAttributes = extensionAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogDataTierPriceInterface catalogDataTierPriceInterface = (CatalogDataTierPriceInterface) o;
    return Objects.equals(this.price, catalogDataTierPriceInterface.price) &&
        Objects.equals(this.priceType, catalogDataTierPriceInterface.priceType) &&
        Objects.equals(this.websiteId, catalogDataTierPriceInterface.websiteId) &&
        Objects.equals(this.sku, catalogDataTierPriceInterface.sku) &&
        Objects.equals(this.customerGroup, catalogDataTierPriceInterface.customerGroup) &&
        Objects.equals(this.quantity, catalogDataTierPriceInterface.quantity) &&
        Objects.equals(this.extensionAttributes, catalogDataTierPriceInterface.extensionAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(price, priceType, websiteId, sku, customerGroup, quantity, extensionAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogDataTierPriceInterface {\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceType: ").append(toIndentedString(priceType)).append("\n");
    sb.append("    websiteId: ").append(toIndentedString(websiteId)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    customerGroup: ").append(toIndentedString(customerGroup)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    extensionAttributes: ").append(toIndentedString(extensionAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

