/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;


/**
 * CMS page interface.
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class CmsDataPageInterface {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_IDENTIFIER = "identifier";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER)
  private String identifier;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_PAGE_LAYOUT = "page_layout";
  @SerializedName(SERIALIZED_NAME_PAGE_LAYOUT)
  private String pageLayout;

  public static final String SERIALIZED_NAME_META_TITLE = "meta_title";
  @SerializedName(SERIALIZED_NAME_META_TITLE)
  private String metaTitle;

  public static final String SERIALIZED_NAME_META_KEYWORDS = "meta_keywords";
  @SerializedName(SERIALIZED_NAME_META_KEYWORDS)
  private String metaKeywords;

  public static final String SERIALIZED_NAME_META_DESCRIPTION = "meta_description";
  @SerializedName(SERIALIZED_NAME_META_DESCRIPTION)
  private String metaDescription;

  public static final String SERIALIZED_NAME_CONTENT_HEADING = "content_heading";
  @SerializedName(SERIALIZED_NAME_CONTENT_HEADING)
  private String contentHeading;

  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  private String content;

  public static final String SERIALIZED_NAME_CREATION_TIME = "creation_time";
  @SerializedName(SERIALIZED_NAME_CREATION_TIME)
  private String creationTime;

  public static final String SERIALIZED_NAME_UPDATE_TIME = "update_time";
  @SerializedName(SERIALIZED_NAME_UPDATE_TIME)
  private String updateTime;

  public static final String SERIALIZED_NAME_SORT_ORDER = "sort_order";
  @SerializedName(SERIALIZED_NAME_SORT_ORDER)
  private String sortOrder;

  public static final String SERIALIZED_NAME_LAYOUT_UPDATE_XML = "layout_update_xml";
  @SerializedName(SERIALIZED_NAME_LAYOUT_UPDATE_XML)
  private String layoutUpdateXml;

  public static final String SERIALIZED_NAME_CUSTOM_THEME = "custom_theme";
  @SerializedName(SERIALIZED_NAME_CUSTOM_THEME)
  private String customTheme;

  public static final String SERIALIZED_NAME_CUSTOM_ROOT_TEMPLATE = "custom_root_template";
  @SerializedName(SERIALIZED_NAME_CUSTOM_ROOT_TEMPLATE)
  private String customRootTemplate;

  public static final String SERIALIZED_NAME_CUSTOM_LAYOUT_UPDATE_XML = "custom_layout_update_xml";
  @SerializedName(SERIALIZED_NAME_CUSTOM_LAYOUT_UPDATE_XML)
  private String customLayoutUpdateXml;

  public static final String SERIALIZED_NAME_CUSTOM_THEME_FROM = "custom_theme_from";
  @SerializedName(SERIALIZED_NAME_CUSTOM_THEME_FROM)
  private String customThemeFrom;

  public static final String SERIALIZED_NAME_CUSTOM_THEME_TO = "custom_theme_to";
  @SerializedName(SERIALIZED_NAME_CUSTOM_THEME_TO)
  private String customThemeTo;

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;


  public CmsDataPageInterface id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * ID
   * @return id
  **/



  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public CmsDataPageInterface identifier(String identifier) {
    
    this.identifier = identifier;
    return this;
  }

   /**
   * Identifier
   * @return identifier
  **/


  public String getIdentifier() {
    return identifier;
  }


  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }


  public CmsDataPageInterface title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Title
   * @return title
  **/



  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public CmsDataPageInterface pageLayout(String pageLayout) {
    
    this.pageLayout = pageLayout;
    return this;
  }

   /**
   * Page layout
   * @return pageLayout
  **/



  public String getPageLayout() {
    return pageLayout;
  }


  public void setPageLayout(String pageLayout) {
    this.pageLayout = pageLayout;
  }


  public CmsDataPageInterface metaTitle(String metaTitle) {
    
    this.metaTitle = metaTitle;
    return this;
  }

   /**
   * Meta title
   * @return metaTitle
  **/



  public String getMetaTitle() {
    return metaTitle;
  }


  public void setMetaTitle(String metaTitle) {
    this.metaTitle = metaTitle;
  }


  public CmsDataPageInterface metaKeywords(String metaKeywords) {
    
    this.metaKeywords = metaKeywords;
    return this;
  }

   /**
   * Meta keywords
   * @return metaKeywords
  **/



  public String getMetaKeywords() {
    return metaKeywords;
  }


  public void setMetaKeywords(String metaKeywords) {
    this.metaKeywords = metaKeywords;
  }


  public CmsDataPageInterface metaDescription(String metaDescription) {
    
    this.metaDescription = metaDescription;
    return this;
  }

   /**
   * Meta description
   * @return metaDescription
  **/



  public String getMetaDescription() {
    return metaDescription;
  }


  public void setMetaDescription(String metaDescription) {
    this.metaDescription = metaDescription;
  }


  public CmsDataPageInterface contentHeading(String contentHeading) {
    
    this.contentHeading = contentHeading;
    return this;
  }

   /**
   * Content heading
   * @return contentHeading
  **/



  public String getContentHeading() {
    return contentHeading;
  }


  public void setContentHeading(String contentHeading) {
    this.contentHeading = contentHeading;
  }


  public CmsDataPageInterface content(String content) {
    
    this.content = content;
    return this;
  }

   /**
   * Content
   * @return content
  **/



  public String getContent() {
    return content;
  }


  public void setContent(String content) {
    this.content = content;
  }


  public CmsDataPageInterface creationTime(String creationTime) {
    
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Creation time
   * @return creationTime
  **/



  public String getCreationTime() {
    return creationTime;
  }


  public void setCreationTime(String creationTime) {
    this.creationTime = creationTime;
  }


  public CmsDataPageInterface updateTime(String updateTime) {
    
    this.updateTime = updateTime;
    return this;
  }

   /**
   * Update time
   * @return updateTime
  **/



  public String getUpdateTime() {
    return updateTime;
  }


  public void setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
  }


  public CmsDataPageInterface sortOrder(String sortOrder) {
    
    this.sortOrder = sortOrder;
    return this;
  }

   /**
   * Sort order
   * @return sortOrder
  **/



  public String getSortOrder() {
    return sortOrder;
  }


  public void setSortOrder(String sortOrder) {
    this.sortOrder = sortOrder;
  }


  public CmsDataPageInterface layoutUpdateXml(String layoutUpdateXml) {
    
    this.layoutUpdateXml = layoutUpdateXml;
    return this;
  }

   /**
   * Layout update xml
   * @return layoutUpdateXml
  **/



  public String getLayoutUpdateXml() {
    return layoutUpdateXml;
  }


  public void setLayoutUpdateXml(String layoutUpdateXml) {
    this.layoutUpdateXml = layoutUpdateXml;
  }


  public CmsDataPageInterface customTheme(String customTheme) {
    
    this.customTheme = customTheme;
    return this;
  }

   /**
   * Custom theme
   * @return customTheme
  **/



  public String getCustomTheme() {
    return customTheme;
  }


  public void setCustomTheme(String customTheme) {
    this.customTheme = customTheme;
  }


  public CmsDataPageInterface customRootTemplate(String customRootTemplate) {
    
    this.customRootTemplate = customRootTemplate;
    return this;
  }

   /**
   * Custom root template
   * @return customRootTemplate
  **/



  public String getCustomRootTemplate() {
    return customRootTemplate;
  }


  public void setCustomRootTemplate(String customRootTemplate) {
    this.customRootTemplate = customRootTemplate;
  }


  public CmsDataPageInterface customLayoutUpdateXml(String customLayoutUpdateXml) {
    
    this.customLayoutUpdateXml = customLayoutUpdateXml;
    return this;
  }

   /**
   * Custom layout update xml
   * @return customLayoutUpdateXml
  **/



  public String getCustomLayoutUpdateXml() {
    return customLayoutUpdateXml;
  }


  public void setCustomLayoutUpdateXml(String customLayoutUpdateXml) {
    this.customLayoutUpdateXml = customLayoutUpdateXml;
  }


  public CmsDataPageInterface customThemeFrom(String customThemeFrom) {
    
    this.customThemeFrom = customThemeFrom;
    return this;
  }

   /**
   * Custom theme from
   * @return customThemeFrom
  **/



  public String getCustomThemeFrom() {
    return customThemeFrom;
  }


  public void setCustomThemeFrom(String customThemeFrom) {
    this.customThemeFrom = customThemeFrom;
  }


  public CmsDataPageInterface customThemeTo(String customThemeTo) {
    
    this.customThemeTo = customThemeTo;
    return this;
  }

   /**
   * Custom theme to
   * @return customThemeTo
  **/



  public String getCustomThemeTo() {
    return customThemeTo;
  }


  public void setCustomThemeTo(String customThemeTo) {
    this.customThemeTo = customThemeTo;
  }


  public CmsDataPageInterface active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Active
   * @return active
  **/



  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CmsDataPageInterface cmsDataPageInterface = (CmsDataPageInterface) o;
    return Objects.equals(this.id, cmsDataPageInterface.id) &&
        Objects.equals(this.identifier, cmsDataPageInterface.identifier) &&
        Objects.equals(this.title, cmsDataPageInterface.title) &&
        Objects.equals(this.pageLayout, cmsDataPageInterface.pageLayout) &&
        Objects.equals(this.metaTitle, cmsDataPageInterface.metaTitle) &&
        Objects.equals(this.metaKeywords, cmsDataPageInterface.metaKeywords) &&
        Objects.equals(this.metaDescription, cmsDataPageInterface.metaDescription) &&
        Objects.equals(this.contentHeading, cmsDataPageInterface.contentHeading) &&
        Objects.equals(this.content, cmsDataPageInterface.content) &&
        Objects.equals(this.creationTime, cmsDataPageInterface.creationTime) &&
        Objects.equals(this.updateTime, cmsDataPageInterface.updateTime) &&
        Objects.equals(this.sortOrder, cmsDataPageInterface.sortOrder) &&
        Objects.equals(this.layoutUpdateXml, cmsDataPageInterface.layoutUpdateXml) &&
        Objects.equals(this.customTheme, cmsDataPageInterface.customTheme) &&
        Objects.equals(this.customRootTemplate, cmsDataPageInterface.customRootTemplate) &&
        Objects.equals(this.customLayoutUpdateXml, cmsDataPageInterface.customLayoutUpdateXml) &&
        Objects.equals(this.customThemeFrom, cmsDataPageInterface.customThemeFrom) &&
        Objects.equals(this.customThemeTo, cmsDataPageInterface.customThemeTo) &&
        Objects.equals(this.active, cmsDataPageInterface.active);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, identifier, title, pageLayout, metaTitle, metaKeywords, metaDescription, contentHeading, content, creationTime, updateTime, sortOrder, layoutUpdateXml, customTheme, customRootTemplate, customLayoutUpdateXml, customThemeFrom, customThemeTo, active);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CmsDataPageInterface {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    pageLayout: ").append(toIndentedString(pageLayout)).append("\n");
    sb.append("    metaTitle: ").append(toIndentedString(metaTitle)).append("\n");
    sb.append("    metaKeywords: ").append(toIndentedString(metaKeywords)).append("\n");
    sb.append("    metaDescription: ").append(toIndentedString(metaDescription)).append("\n");
    sb.append("    contentHeading: ").append(toIndentedString(contentHeading)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    updateTime: ").append(toIndentedString(updateTime)).append("\n");
    sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
    sb.append("    layoutUpdateXml: ").append(toIndentedString(layoutUpdateXml)).append("\n");
    sb.append("    customTheme: ").append(toIndentedString(customTheme)).append("\n");
    sb.append("    customRootTemplate: ").append(toIndentedString(customRootTemplate)).append("\n");
    sb.append("    customLayoutUpdateXml: ").append(toIndentedString(customLayoutUpdateXml)).append("\n");
    sb.append("    customThemeFrom: ").append(toIndentedString(customThemeFrom)).append("\n");
    sb.append("    customThemeTo: ").append(toIndentedString(customThemeTo)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

