/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import com.squareup.moshi.Json;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Credit Limit data transfer object interface.
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class CompanyCreditDataCreditLimitInterface {
  public static final String SERIALIZED_NAME_ID = "id";
  @Json(name = SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_COMPANY_ID = "company_id";
  @Json(name = SERIALIZED_NAME_COMPANY_ID)
  private Integer companyId;

  public static final String SERIALIZED_NAME_CREDIT_LIMIT = "credit_limit";
  @Json(name = SERIALIZED_NAME_CREDIT_LIMIT)
  private BigDecimal creditLimit;

  public static final String SERIALIZED_NAME_BALANCE = "balance";
  @Json(name = SERIALIZED_NAME_BALANCE)
  private BigDecimal balance;

  public static final String SERIALIZED_NAME_CURRENCY_CODE = "currency_code";
  @Json(name = SERIALIZED_NAME_CURRENCY_CODE)
  private String currencyCode;

  public static final String SERIALIZED_NAME_EXCEED_LIMIT = "exceed_limit";
  @Json(name = SERIALIZED_NAME_EXCEED_LIMIT)
  private Boolean exceedLimit;

  public static final String SERIALIZED_NAME_AVAILABLE_LIMIT = "available_limit";
  @Json(name = SERIALIZED_NAME_AVAILABLE_LIMIT)
  private BigDecimal availableLimit;

  public static final String SERIALIZED_NAME_CREDIT_COMMENT = "credit_comment";
  @Json(name = SERIALIZED_NAME_CREDIT_COMMENT)
  private String creditComment;

  public static final String SERIALIZED_NAME_EXTENSION_ATTRIBUTES = "extension_attributes";
  @Json(name = SERIALIZED_NAME_EXTENSION_ATTRIBUTES)
  private Object extensionAttributes;


  public CompanyCreditDataCreditLimitInterface id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * ID.
   * @return id
  **/
  


  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public CompanyCreditDataCreditLimitInterface companyId(Integer companyId) {
    
    this.companyId = companyId;
    return this;
  }

   /**
   * Company id.
   * @return companyId
  **/
  


  public Integer getCompanyId() {
    return companyId;
  }


  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }


  public CompanyCreditDataCreditLimitInterface creditLimit(BigDecimal creditLimit) {
    
    this.creditLimit = creditLimit;
    return this;
  }

   /**
   * Credit Limit.
   * @return creditLimit
  **/
  


  public BigDecimal getCreditLimit() {
    return creditLimit;
  }


  public void setCreditLimit(BigDecimal creditLimit) {
    this.creditLimit = creditLimit;
  }


  public CompanyCreditDataCreditLimitInterface balance(BigDecimal balance) {
    
    this.balance = balance;
    return this;
  }

   /**
   * Balance.
   * @return balance
  **/
  


  public BigDecimal getBalance() {
    return balance;
  }


  public void setBalance(BigDecimal balance) {
    this.balance = balance;
  }


  public CompanyCreditDataCreditLimitInterface currencyCode(String currencyCode) {
    
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Currency Code.
   * @return currencyCode
  **/
  


  public String getCurrencyCode() {
    return currencyCode;
  }


  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }


  public CompanyCreditDataCreditLimitInterface exceedLimit(Boolean exceedLimit) {
    
    this.exceedLimit = exceedLimit;
    return this;
  }

   /**
   * Exceed Limit.
   * @return exceedLimit
  **/
  

  public Boolean getExceedLimit() {
    return exceedLimit;
  }


  public void setExceedLimit(Boolean exceedLimit) {
    this.exceedLimit = exceedLimit;
  }


  public CompanyCreditDataCreditLimitInterface availableLimit(BigDecimal availableLimit) {
    
    this.availableLimit = availableLimit;
    return this;
  }

   /**
   * Available Limit.
   * @return availableLimit
  **/
  


  public BigDecimal getAvailableLimit() {
    return availableLimit;
  }


  public void setAvailableLimit(BigDecimal availableLimit) {
    this.availableLimit = availableLimit;
  }


  public CompanyCreditDataCreditLimitInterface creditComment(String creditComment) {
    
    this.creditComment = creditComment;
    return this;
  }

   /**
   * Credit comment for company credit history.
   * @return creditComment
  **/
  


  public String getCreditComment() {
    return creditComment;
  }


  public void setCreditComment(String creditComment) {
    this.creditComment = creditComment;
  }


  public CompanyCreditDataCreditLimitInterface extensionAttributes(Object extensionAttributes) {
    
    this.extensionAttributes = extensionAttributes;
    return this;
  }

   /**
   * ExtensionInterface class for @see \\Magento\\CompanyCredit\\Api\\Data\\CreditLimitInterface
   * @return extensionAttributes
  **/
  


  public Object getExtensionAttributes() {
    return extensionAttributes;
  }


  public void setExtensionAttributes(Object extensionAttributes) {
    this.extensionAttributes = extensionAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyCreditDataCreditLimitInterface companyCreditDataCreditLimitInterface = (CompanyCreditDataCreditLimitInterface) o;
    return Objects.equals(this.id, companyCreditDataCreditLimitInterface.id) &&
        Objects.equals(this.companyId, companyCreditDataCreditLimitInterface.companyId) &&
        Objects.equals(this.creditLimit, companyCreditDataCreditLimitInterface.creditLimit) &&
        Objects.equals(this.balance, companyCreditDataCreditLimitInterface.balance) &&
        Objects.equals(this.currencyCode, companyCreditDataCreditLimitInterface.currencyCode) &&
        Objects.equals(this.exceedLimit, companyCreditDataCreditLimitInterface.exceedLimit) &&
        Objects.equals(this.availableLimit, companyCreditDataCreditLimitInterface.availableLimit) &&
        Objects.equals(this.creditComment, companyCreditDataCreditLimitInterface.creditComment) &&
        Objects.equals(this.extensionAttributes, companyCreditDataCreditLimitInterface.extensionAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, companyId, creditLimit, balance, currencyCode, exceedLimit, availableLimit, creditComment, extensionAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyCreditDataCreditLimitInterface {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    creditLimit: ").append(toIndentedString(creditLimit)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    exceedLimit: ").append(toIndentedString(exceedLimit)).append("\n");
    sb.append("    availableLimit: ").append(toIndentedString(availableLimit)).append("\n");
    sb.append("    creditComment: ").append(toIndentedString(creditComment)).append("\n");
    sb.append("    extensionAttributes: ").append(toIndentedString(extensionAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

