/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Error details
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class ErrorErrorsItem {
  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  private List<ErrorParametersItem> parameters = null;


  public ErrorErrorsItem message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Error message
   * @return message
  **/



  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public ErrorErrorsItem parameters(List<ErrorParametersItem> parameters) {
    
    this.parameters = parameters;
    return this;
  }

  public ErrorErrorsItem addParametersItem(ErrorParametersItem parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<ErrorParametersItem>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * Error parameters list
   * @return parameters
  **/



  public List<ErrorParametersItem> getParameters() {
    return parameters;
  }


  public void setParameters(List<ErrorParametersItem> parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorErrorsItem errorErrorsItem = (ErrorErrorsItem) o;
    return Objects.equals(this.message, errorErrorsItem.message) &&
        Objects.equals(this.parameters, errorErrorsItem.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, parameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorErrorsItem {\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

