/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;


/**
 * Interface for custom attribute value.
 */

public class FrameworkAttributeInterface {
  public static final String SERIALIZED_NAME_ATTRIBUTE_CODE = "attribute_code";

  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_CODE)
  private String attributeCode;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private List value = new ArrayList();


  public FrameworkAttributeInterface attributeCode(String attributeCode) {
    
    this.attributeCode = attributeCode;
    return this;
  }

   /**
   * Attribute code
   * @return attributeCode
  **/
  

  public String getAttributeCode() {
    return attributeCode;
  }


  public void setAttributeCode(String attributeCode) {
    this.attributeCode = attributeCode;
  }


  public FrameworkAttributeInterface value(String attributeCode, List value) {
    
    this.value = value;
    return this;
  }

   /**
   * Attribute value
   * @return value
  **/
  

  public List getValue() {
    return value;
  }


  public void setValue(List value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FrameworkAttributeInterface frameworkAttributeInterface = (FrameworkAttributeInterface) o;
    return Objects.equals(this.attributeCode, frameworkAttributeInterface.attributeCode) &&
        Objects.equals(this.value, frameworkAttributeInterface.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeCode, value);
  }


  @Override
  public String toString() {
    String sb = "class FrameworkAttributeInterface {\n" +
            "    attributeCode: " + toIndentedString(attributeCode) + "\n" +
            "    value: " + toIndentedString(value) + "\n" +
            "}";
    return sb;
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

