/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import com.squareup.moshi.Json;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Interface Aggregation Value
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class FrameworkSearchAggregationValueInterface {
  public static final String SERIALIZED_NAME_VALUE = "value";
  @Json(name = SERIALIZED_NAME_VALUE)
  private String value;

  public static final String SERIALIZED_NAME_METRICS = "metrics";
  @Json(name = SERIALIZED_NAME_METRICS)
  private List<String> metrics = new ArrayList<String>();


  public FrameworkSearchAggregationValueInterface value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Aggregation
   * @return value
  **/
  

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  public FrameworkSearchAggregationValueInterface metrics(List<String> metrics) {
    
    this.metrics = metrics;
    return this;
  }

  public FrameworkSearchAggregationValueInterface addMetricsItem(String metricsItem) {
    this.metrics.add(metricsItem);
    return this;
  }

   /**
   * Metrics
   * @return metrics
  **/
  

  public List<String> getMetrics() {
    return metrics;
  }


  public void setMetrics(List<String> metrics) {
    this.metrics = metrics;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FrameworkSearchAggregationValueInterface frameworkSearchAggregationValueInterface = (FrameworkSearchAggregationValueInterface) o;
    return Objects.equals(this.value, frameworkSearchAggregationValueInterface.value) &&
        Objects.equals(this.metrics, frameworkSearchAggregationValueInterface.metrics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, metrics);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FrameworkSearchAggregationValueInterface {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

