/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;


/**
 * Represents &#x60;product item id with qty&#x60; of a grouped product.
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class GroupedProductDataGroupedOptionsInterface {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_QTY = "qty";
  @SerializedName(SERIALIZED_NAME_QTY)
  private Integer qty;

  public static final String SERIALIZED_NAME_EXTENSION_ATTRIBUTES = "extension_attributes";
  @SerializedName(SERIALIZED_NAME_EXTENSION_ATTRIBUTES)
  private Object extensionAttributes;


  public GroupedProductDataGroupedOptionsInterface id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Associated product id
   * @return id
  **/



  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public GroupedProductDataGroupedOptionsInterface qty(Integer qty) {
    
    this.qty = qty;
    return this;
  }

   /**
   * Associated product qty
   * @return qty
  **/



  public Integer getQty() {
    return qty;
  }


  public void setQty(Integer qty) {
    this.qty = qty;
  }


  public GroupedProductDataGroupedOptionsInterface extensionAttributes(Object extensionAttributes) {
    
    this.extensionAttributes = extensionAttributes;
    return this;
  }

   /**
   * ExtensionInterface class for @see \\Magento\\GroupedProduct\\Api\\Data\\GroupedOptionsInterface
   * @return extensionAttributes
  **/



  public Object getExtensionAttributes() {
    return extensionAttributes;
  }


  public void setExtensionAttributes(Object extensionAttributes) {
    this.extensionAttributes = extensionAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupedProductDataGroupedOptionsInterface groupedProductDataGroupedOptionsInterface = (GroupedProductDataGroupedOptionsInterface) o;
    return Objects.equals(this.id, groupedProductDataGroupedOptionsInterface.id) &&
        Objects.equals(this.qty, groupedProductDataGroupedOptionsInterface.qty) &&
        Objects.equals(this.extensionAttributes, groupedProductDataGroupedOptionsInterface.extensionAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, qty, extensionAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupedProductDataGroupedOptionsInterface {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    qty: ").append(toIndentedString(qty)).append("\n");
    sb.append("    extensionAttributes: ").append(toIndentedString(extensionAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

