/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;


/**
 * InlineObject53
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class InlineObject53 {
  public static final String SERIALIZED_NAME_TFA_TOKEN = "tfaToken";
  @SerializedName(SERIALIZED_NAME_TFA_TOKEN)
  private String tfaToken;

  public static final String SERIALIZED_NAME_DEVICE_DATA = "deviceData";
  @SerializedName(SERIALIZED_NAME_DEVICE_DATA)
  private TwoFactorAuthDataAuthyDeviceInterface deviceData;


  public InlineObject53 tfaToken(String tfaToken) {
    
    this.tfaToken = tfaToken;
    return this;
  }

   /**
   * Get tfaToken
   * @return tfaToken
  **/


  public String getTfaToken() {
    return tfaToken;
  }


  public void setTfaToken(String tfaToken) {
    this.tfaToken = tfaToken;
  }


  public InlineObject53 deviceData(TwoFactorAuthDataAuthyDeviceInterface deviceData) {
    
    this.deviceData = deviceData;
    return this;
  }

   /**
   * Get deviceData
   * @return deviceData
  **/


  public TwoFactorAuthDataAuthyDeviceInterface getDeviceData() {
    return deviceData;
  }


  public void setDeviceData(TwoFactorAuthDataAuthyDeviceInterface deviceData) {
    this.deviceData = deviceData;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject53 inlineObject53 = (InlineObject53) o;
    return Objects.equals(this.tfaToken, inlineObject53.tfaToken) &&
        Objects.equals(this.deviceData, inlineObject53.deviceData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tfaToken, deviceData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject53 {\n");
    sb.append("    tfaToken: ").append(toIndentedString(tfaToken)).append("\n");
    sb.append("    deviceData: ").append(toIndentedString(deviceData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

