/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * InlineObject36
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class InlineObject36 {
  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<SalesDataShipmentItemCreationInterface> items = null;

  public static final String SERIALIZED_NAME_NOTIFY = "notify";
  @SerializedName(SERIALIZED_NAME_NOTIFY)
  private Boolean notify;

  public static final String SERIALIZED_NAME_APPEND_COMMENT = "appendComment";
  @SerializedName(SERIALIZED_NAME_APPEND_COMMENT)
  private Boolean appendComment;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  private SalesDataShipmentCommentCreationInterface comment;

  public static final String SERIALIZED_NAME_TRACKS = "tracks";
  @SerializedName(SERIALIZED_NAME_TRACKS)
  private List<SalesDataShipmentTrackCreationInterface> tracks = null;

  public static final String SERIALIZED_NAME_PACKAGES = "packages";
  @SerializedName(SERIALIZED_NAME_PACKAGES)
  private List<SalesDataShipmentPackageCreationInterface> packages = null;

  public static final String SERIALIZED_NAME_ARGUMENTS = "arguments";
  @SerializedName(SERIALIZED_NAME_ARGUMENTS)
  private SalesDataShipmentCreationArgumentsInterface arguments;


  public InlineObject36 items(List<SalesDataShipmentItemCreationInterface> items) {
    
    this.items = items;
    return this;
  }

  public InlineObject36 addItemsItem(SalesDataShipmentItemCreationInterface itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<SalesDataShipmentItemCreationInterface>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/

  

  public List<SalesDataShipmentItemCreationInterface> getItems() {
    return items;
  }


  public void setItems(List<SalesDataShipmentItemCreationInterface> items) {
    this.items = items;
  }


  public InlineObject36 notify(Boolean notify) {
    
    this.notify = notify;
    return this;
  }

   /**
   * Get notify
   * @return notify
  **/

  

  public Boolean getNotify() {
    return notify;
  }


  public void setNotify(Boolean notify) {
    this.notify = notify;
  }


  public InlineObject36 appendComment(Boolean appendComment) {
    
    this.appendComment = appendComment;
    return this;
  }

   /**
   * Get appendComment
   * @return appendComment
  **/

  

  public Boolean getAppendComment() {
    return appendComment;
  }


  public void setAppendComment(Boolean appendComment) {
    this.appendComment = appendComment;
  }


  public InlineObject36 comment(SalesDataShipmentCommentCreationInterface comment) {
    
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/

  

  public SalesDataShipmentCommentCreationInterface getComment() {
    return comment;
  }


  public void setComment(SalesDataShipmentCommentCreationInterface comment) {
    this.comment = comment;
  }


  public InlineObject36 tracks(List<SalesDataShipmentTrackCreationInterface> tracks) {
    
    this.tracks = tracks;
    return this;
  }

  public InlineObject36 addTracksItem(SalesDataShipmentTrackCreationInterface tracksItem) {
    if (this.tracks == null) {
      this.tracks = new ArrayList<SalesDataShipmentTrackCreationInterface>();
    }
    this.tracks.add(tracksItem);
    return this;
  }

   /**
   * Get tracks
   * @return tracks
  **/

  

  public List<SalesDataShipmentTrackCreationInterface> getTracks() {
    return tracks;
  }


  public void setTracks(List<SalesDataShipmentTrackCreationInterface> tracks) {
    this.tracks = tracks;
  }


  public InlineObject36 packages(List<SalesDataShipmentPackageCreationInterface> packages) {
    
    this.packages = packages;
    return this;
  }

  public InlineObject36 addPackagesItem(SalesDataShipmentPackageCreationInterface packagesItem) {
    if (this.packages == null) {
      this.packages = new ArrayList<SalesDataShipmentPackageCreationInterface>();
    }
    this.packages.add(packagesItem);
    return this;
  }

   /**
   * Get packages
   * @return packages
  **/

  

  public List<SalesDataShipmentPackageCreationInterface> getPackages() {
    return packages;
  }


  public void setPackages(List<SalesDataShipmentPackageCreationInterface> packages) {
    this.packages = packages;
  }


  public InlineObject36 arguments(SalesDataShipmentCreationArgumentsInterface arguments) {
    
    this.arguments = arguments;
    return this;
  }

   /**
   * Get arguments
   * @return arguments
  **/

  

  public SalesDataShipmentCreationArgumentsInterface getArguments() {
    return arguments;
  }


  public void setArguments(SalesDataShipmentCreationArgumentsInterface arguments) {
    this.arguments = arguments;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject36 inlineObject36 = (InlineObject36) o;
    return Objects.equals(this.items, inlineObject36.items) &&
        Objects.equals(this.notify, inlineObject36.notify) &&
        Objects.equals(this.appendComment, inlineObject36.appendComment) &&
        Objects.equals(this.comment, inlineObject36.comment) &&
        Objects.equals(this.tracks, inlineObject36.tracks) &&
        Objects.equals(this.packages, inlineObject36.packages) &&
        Objects.equals(this.arguments, inlineObject36.arguments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items, notify, appendComment, comment, tracks, packages, arguments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject36 {\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    notify: ").append(toIndentedString(notify)).append("\n");
    sb.append("    appendComment: ").append(toIndentedString(appendComment)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    tracks: ").append(toIndentedString(tracks)).append("\n");
    sb.append("    packages: ").append(toIndentedString(packages)).append("\n");
    sb.append("    arguments: ").append(toIndentedString(arguments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

