/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;


/**
 * InlineObject19
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class InlineObject19 {
  public static final String SERIALIZED_NAME_ENTITY_TYPE_CODE = "entityTypeCode";
  @SerializedName(SERIALIZED_NAME_ENTITY_TYPE_CODE)
  private String entityTypeCode;

  public static final String SERIALIZED_NAME_ATTRIBUTE_SET = "attributeSet";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_SET)
  private EavDataAttributeSetInterface attributeSet;

  public static final String SERIALIZED_NAME_SKELETON_ID = "skeletonId";
  @SerializedName(SERIALIZED_NAME_SKELETON_ID)
  private Integer skeletonId;


  public InlineObject19 entityTypeCode(String entityTypeCode) {
    
    this.entityTypeCode = entityTypeCode;
    return this;
  }

   /**
   * Get entityTypeCode
   * @return entityTypeCode
  **/
  

  public String getEntityTypeCode() {
    return entityTypeCode;
  }


  public void setEntityTypeCode(String entityTypeCode) {
    this.entityTypeCode = entityTypeCode;
  }


  public InlineObject19 attributeSet(EavDataAttributeSetInterface attributeSet) {
    
    this.attributeSet = attributeSet;
    return this;
  }

   /**
   * Get attributeSet
   * @return attributeSet
  **/
  

  public EavDataAttributeSetInterface getAttributeSet() {
    return attributeSet;
  }


  public void setAttributeSet(EavDataAttributeSetInterface attributeSet) {
    this.attributeSet = attributeSet;
  }


  public InlineObject19 skeletonId(Integer skeletonId) {
    
    this.skeletonId = skeletonId;
    return this;
  }

   /**
   * Get skeletonId
   * @return skeletonId
  **/
  

  public Integer getSkeletonId() {
    return skeletonId;
  }


  public void setSkeletonId(Integer skeletonId) {
    this.skeletonId = skeletonId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject19 inlineObject19 = (InlineObject19) o;
    return Objects.equals(this.entityTypeCode, inlineObject19.entityTypeCode) &&
        Objects.equals(this.attributeSet, inlineObject19.attributeSet) &&
        Objects.equals(this.skeletonId, inlineObject19.skeletonId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityTypeCode, attributeSet, skeletonId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject19 {\n");
    sb.append("    entityTypeCode: ").append(toIndentedString(entityTypeCode)).append("\n");
    sb.append("    attributeSet: ").append(toIndentedString(attributeSet)).append("\n");
    sb.append("    skeletonId: ").append(toIndentedString(skeletonId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

