/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import com.squareup.moshi.Json;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents result of service Magento\\InventorySalesApi\\Api\\IsProductSalableForRequestedQtyInterface::execute
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class InventorySalesApiDataProductSalableResultInterface {
  public static final String SERIALIZED_NAME_SALABLE = "salable";
  @Json(name = SERIALIZED_NAME_SALABLE)
  private Boolean salable;

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @Json(name = SERIALIZED_NAME_ERRORS)
  private List<InventorySalesApiDataProductSalabilityErrorInterface> errors = new ArrayList<InventorySalesApiDataProductSalabilityErrorInterface>();

  public static final String SERIALIZED_NAME_EXTENSION_ATTRIBUTES = "extension_attributes";
  @Json(name = SERIALIZED_NAME_EXTENSION_ATTRIBUTES)
  private Object extensionAttributes;


  public InventorySalesApiDataProductSalableResultInterface salable(Boolean salable) {
    
    this.salable = salable;
    return this;
  }

   /**
   * Get salable
   * @return salable
  **/
  

  public Boolean getSalable() {
    return salable;
  }


  public void setSalable(Boolean salable) {
    this.salable = salable;
  }


  public InventorySalesApiDataProductSalableResultInterface errors(List<InventorySalesApiDataProductSalabilityErrorInterface> errors) {
    
    this.errors = errors;
    return this;
  }

  public InventorySalesApiDataProductSalableResultInterface addErrorsItem(InventorySalesApiDataProductSalabilityErrorInterface errorsItem) {
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * Get errors
   * @return errors
  **/
  

  public List<InventorySalesApiDataProductSalabilityErrorInterface> getErrors() {
    return errors;
  }


  public void setErrors(List<InventorySalesApiDataProductSalabilityErrorInterface> errors) {
    this.errors = errors;
  }


  public InventorySalesApiDataProductSalableResultInterface extensionAttributes(Object extensionAttributes) {
    
    this.extensionAttributes = extensionAttributes;
    return this;
  }

   /**
   * ExtensionInterface class for @see \\Magento\\InventorySalesApi\\Api\\Data\\ProductSalableResultInterface
   * @return extensionAttributes
  **/
  


  public Object getExtensionAttributes() {
    return extensionAttributes;
  }


  public void setExtensionAttributes(Object extensionAttributes) {
    this.extensionAttributes = extensionAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventorySalesApiDataProductSalableResultInterface inventorySalesApiDataProductSalableResultInterface = (InventorySalesApiDataProductSalableResultInterface) o;
    return Objects.equals(this.salable, inventorySalesApiDataProductSalableResultInterface.salable) &&
        Objects.equals(this.errors, inventorySalesApiDataProductSalableResultInterface.errors) &&
        Objects.equals(this.extensionAttributes, inventorySalesApiDataProductSalableResultInterface.extensionAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(salable, errors, extensionAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventorySalesApiDataProductSalableResultInterface {\n");
    sb.append("    salable: ").append(toIndentedString(salable)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    extensionAttributes: ").append(toIndentedString(extensionAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

