/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import com.squareup.moshi.Json;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;


/**
 * Interface PaymentMethodInterface
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class QuoteDataPaymentMethodInterface {
  public static final String SERIALIZED_NAME_CODE = "code";
  @Json(name = SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @Json(name = SERIALIZED_NAME_TITLE)
  private String title;


  public QuoteDataPaymentMethodInterface code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Payment method code
   * @return code
  **/


  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public QuoteDataPaymentMethodInterface title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Payment method title
   * @return title
  **/


  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuoteDataPaymentMethodInterface quoteDataPaymentMethodInterface = (QuoteDataPaymentMethodInterface) o;
    return Objects.equals(this.code, quoteDataPaymentMethodInterface.code) &&
        Objects.equals(this.title, quoteDataPaymentMethodInterface.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuoteDataPaymentMethodInterface {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

