/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;


/**
 * Interface CouponInterface
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class SalesRuleDataCouponInterface {
  public static final String SERIALIZED_NAME_COUPON_ID = "coupon_id";
  @SerializedName(SERIALIZED_NAME_COUPON_ID)
  private Integer couponId;

  public static final String SERIALIZED_NAME_RULE_ID = "rule_id";
  @SerializedName(SERIALIZED_NAME_RULE_ID)
  private Integer ruleId;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_USAGE_LIMIT = "usage_limit";
  @SerializedName(SERIALIZED_NAME_USAGE_LIMIT)
  private Integer usageLimit;

  public static final String SERIALIZED_NAME_USAGE_PER_CUSTOMER = "usage_per_customer";
  @SerializedName(SERIALIZED_NAME_USAGE_PER_CUSTOMER)
  private Integer usagePerCustomer;

  public static final String SERIALIZED_NAME_TIMES_USED = "times_used";
  @SerializedName(SERIALIZED_NAME_TIMES_USED)
  private Integer timesUsed;

  public static final String SERIALIZED_NAME_EXPIRATION_DATE = "expiration_date";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_DATE)
  private String expirationDate;

  public static final String SERIALIZED_NAME_IS_PRIMARY = "is_primary";
  @SerializedName(SERIALIZED_NAME_IS_PRIMARY)
  private Boolean isPrimary;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private Integer type;

  public static final String SERIALIZED_NAME_EXTENSION_ATTRIBUTES = "extension_attributes";
  @SerializedName(SERIALIZED_NAME_EXTENSION_ATTRIBUTES)
  private Object extensionAttributes;


  public SalesRuleDataCouponInterface couponId(Integer couponId) {
    
    this.couponId = couponId;
    return this;
  }

   /**
   * Coupon id
   * @return couponId
  **/
  


  public Integer getCouponId() {
    return couponId;
  }


  public void setCouponId(Integer couponId) {
    this.couponId = couponId;
  }


  public SalesRuleDataCouponInterface ruleId(Integer ruleId) {
    
    this.ruleId = ruleId;
    return this;
  }

   /**
   * The id of the rule associated with the coupon
   * @return ruleId
  **/


  public Integer getRuleId() {
    return ruleId;
  }


  public void setRuleId(Integer ruleId) {
    this.ruleId = ruleId;
  }


  public SalesRuleDataCouponInterface code(String code) {
    
    this.code = code;
    return this;
  }

   /**
   * Coupon code
   * @return code
  **/
  


  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public SalesRuleDataCouponInterface usageLimit(Integer usageLimit) {
    
    this.usageLimit = usageLimit;
    return this;
  }

   /**
   * Usage limit
   * @return usageLimit
  **/
  


  public Integer getUsageLimit() {
    return usageLimit;
  }


  public void setUsageLimit(Integer usageLimit) {
    this.usageLimit = usageLimit;
  }


  public SalesRuleDataCouponInterface usagePerCustomer(Integer usagePerCustomer) {
    
    this.usagePerCustomer = usagePerCustomer;
    return this;
  }

   /**
   * Usage limit per customer
   * @return usagePerCustomer
  **/
  


  public Integer getUsagePerCustomer() {
    return usagePerCustomer;
  }


  public void setUsagePerCustomer(Integer usagePerCustomer) {
    this.usagePerCustomer = usagePerCustomer;
  }


  public SalesRuleDataCouponInterface timesUsed(Integer timesUsed) {
    
    this.timesUsed = timesUsed;
    return this;
  }

   /**
   * The number of times the coupon has been used
   * @return timesUsed
  **/


  public Integer getTimesUsed() {
    return timesUsed;
  }


  public void setTimesUsed(Integer timesUsed) {
    this.timesUsed = timesUsed;
  }


  public SalesRuleDataCouponInterface expirationDate(String expirationDate) {
    
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Expiration date
   * @return expirationDate
  **/
  


  public String getExpirationDate() {
    return expirationDate;
  }


  public void setExpirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
  }


  public SalesRuleDataCouponInterface isPrimary(Boolean isPrimary) {
    
    this.isPrimary = isPrimary;
    return this;
  }

   /**
   * The coupon is primary coupon for the rule that it&#39;s associated with
   * @return isPrimary
  **/


  public Boolean getIsPrimary() {
    return isPrimary;
  }


  public void setIsPrimary(Boolean isPrimary) {
    this.isPrimary = isPrimary;
  }


  public SalesRuleDataCouponInterface createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * When the coupon is created
   * @return createdAt
  **/
  


  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public SalesRuleDataCouponInterface type(Integer type) {
    
    this.type = type;
    return this;
  }

   /**
   * Of coupon
   * @return type
  **/
  


  public Integer getType() {
    return type;
  }


  public void setType(Integer type) {
    this.type = type;
  }


  public SalesRuleDataCouponInterface extensionAttributes(Object extensionAttributes) {
    
    this.extensionAttributes = extensionAttributes;
    return this;
  }

   /**
   * ExtensionInterface class for @see \\Magento\\SalesRule\\Api\\Data\\CouponInterface
   * @return extensionAttributes
  **/
  


  public Object getExtensionAttributes() {
    return extensionAttributes;
  }


  public void setExtensionAttributes(Object extensionAttributes) {
    this.extensionAttributes = extensionAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalesRuleDataCouponInterface salesRuleDataCouponInterface = (SalesRuleDataCouponInterface) o;
    return Objects.equals(this.couponId, salesRuleDataCouponInterface.couponId) &&
        Objects.equals(this.ruleId, salesRuleDataCouponInterface.ruleId) &&
        Objects.equals(this.code, salesRuleDataCouponInterface.code) &&
        Objects.equals(this.usageLimit, salesRuleDataCouponInterface.usageLimit) &&
        Objects.equals(this.usagePerCustomer, salesRuleDataCouponInterface.usagePerCustomer) &&
        Objects.equals(this.timesUsed, salesRuleDataCouponInterface.timesUsed) &&
        Objects.equals(this.expirationDate, salesRuleDataCouponInterface.expirationDate) &&
        Objects.equals(this.isPrimary, salesRuleDataCouponInterface.isPrimary) &&
        Objects.equals(this.createdAt, salesRuleDataCouponInterface.createdAt) &&
        Objects.equals(this.type, salesRuleDataCouponInterface.type) &&
        Objects.equals(this.extensionAttributes, salesRuleDataCouponInterface.extensionAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(couponId, ruleId, code, usageLimit, usagePerCustomer, timesUsed, expirationDate, isPrimary, createdAt, type, extensionAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalesRuleDataCouponInterface {\n");
    sb.append("    couponId: ").append(toIndentedString(couponId)).append("\n");
    sb.append("    ruleId: ").append(toIndentedString(ruleId)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    usageLimit: ").append(toIndentedString(usageLimit)).append("\n");
    sb.append("    usagePerCustomer: ").append(toIndentedString(usagePerCustomer)).append("\n");
    sb.append("    timesUsed: ").append(toIndentedString(timesUsed)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    isPrimary: ").append(toIndentedString(isPrimary)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    extensionAttributes: ").append(toIndentedString(extensionAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

