/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import com.squareup.moshi.Json;

import com.google.gson.annotations.SerializedName;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Credit memo interface. After a customer places and pays for an order and an invoice has been issued, the merchant can create a credit memo to refund all or part of the amount paid for any returned or undelivered items. The memo restores funds to the customer account so that the customer can make future purchases.
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class SalesDataCreditmemoInterface {
  public static final String SERIALIZED_NAME_ADJUSTMENT = "adjustment";
  @Json(name = SERIALIZED_NAME_ADJUSTMENT)
  private BigDecimal adjustment;

  public static final String SERIALIZED_NAME_ADJUSTMENT_NEGATIVE = "adjustment_negative";
  @Json(name = SERIALIZED_NAME_ADJUSTMENT_NEGATIVE)
  private BigDecimal adjustmentNegative;

  public static final String SERIALIZED_NAME_ADJUSTMENT_POSITIVE = "adjustment_positive";
  @Json(name = SERIALIZED_NAME_ADJUSTMENT_POSITIVE)
  private BigDecimal adjustmentPositive;

  public static final String SERIALIZED_NAME_BASE_ADJUSTMENT = "base_adjustment";
  @Json(name = SERIALIZED_NAME_BASE_ADJUSTMENT)
  private BigDecimal baseAdjustment;

  public static final String SERIALIZED_NAME_BASE_ADJUSTMENT_NEGATIVE = "base_adjustment_negative";
  @Json(name = SERIALIZED_NAME_BASE_ADJUSTMENT_NEGATIVE)
  private BigDecimal baseAdjustmentNegative;

  public static final String SERIALIZED_NAME_BASE_ADJUSTMENT_POSITIVE = "base_adjustment_positive";
  @Json(name = SERIALIZED_NAME_BASE_ADJUSTMENT_POSITIVE)
  private BigDecimal baseAdjustmentPositive;

  public static final String SERIALIZED_NAME_BASE_CURRENCY_CODE = "base_currency_code";
  @Json(name = SERIALIZED_NAME_BASE_CURRENCY_CODE)
  private String baseCurrencyCode;

  public static final String SERIALIZED_NAME_BASE_DISCOUNT_AMOUNT = "base_discount_amount";
  @Json(name = SERIALIZED_NAME_BASE_DISCOUNT_AMOUNT)
  private BigDecimal baseDiscountAmount;

  public static final String SERIALIZED_NAME_BASE_GRAND_TOTAL = "base_grand_total";
  @Json(name = SERIALIZED_NAME_BASE_GRAND_TOTAL)
  private BigDecimal baseGrandTotal;

  public static final String SERIALIZED_NAME_BASE_DISCOUNT_TAX_COMPENSATION_AMOUNT = "base_discount_tax_compensation_amount";
  @Json(name = SERIALIZED_NAME_BASE_DISCOUNT_TAX_COMPENSATION_AMOUNT)
  private BigDecimal baseDiscountTaxCompensationAmount;

  public static final String SERIALIZED_NAME_BASE_SHIPPING_AMOUNT = "base_shipping_amount";
  @Json(name = SERIALIZED_NAME_BASE_SHIPPING_AMOUNT)
  private BigDecimal baseShippingAmount;

  public static final String SERIALIZED_NAME_BASE_SHIPPING_DISCOUNT_TAX_COMPENSATION_AMNT = "base_shipping_discount_tax_compensation_amnt";
  @Json(name = SERIALIZED_NAME_BASE_SHIPPING_DISCOUNT_TAX_COMPENSATION_AMNT)
  private BigDecimal baseShippingDiscountTaxCompensationAmnt;

  public static final String SERIALIZED_NAME_BASE_SHIPPING_INCL_TAX = "base_shipping_incl_tax";
  @Json(name = SERIALIZED_NAME_BASE_SHIPPING_INCL_TAX)
  private BigDecimal baseShippingInclTax;

  public static final String SERIALIZED_NAME_BASE_SHIPPING_TAX_AMOUNT = "base_shipping_tax_amount";
  @Json(name = SERIALIZED_NAME_BASE_SHIPPING_TAX_AMOUNT)
  private BigDecimal baseShippingTaxAmount;

  public static final String SERIALIZED_NAME_BASE_SUBTOTAL = "base_subtotal";
  @Json(name = SERIALIZED_NAME_BASE_SUBTOTAL)
  private BigDecimal baseSubtotal;

  public static final String SERIALIZED_NAME_BASE_SUBTOTAL_INCL_TAX = "base_subtotal_incl_tax";
  @Json(name = SERIALIZED_NAME_BASE_SUBTOTAL_INCL_TAX)
  private BigDecimal baseSubtotalInclTax;

  public static final String SERIALIZED_NAME_BASE_TAX_AMOUNT = "base_tax_amount";
  @Json(name = SERIALIZED_NAME_BASE_TAX_AMOUNT)
  private BigDecimal baseTaxAmount;

  public static final String SERIALIZED_NAME_BASE_TO_GLOBAL_RATE = "base_to_global_rate";
  @Json(name = SERIALIZED_NAME_BASE_TO_GLOBAL_RATE)
  private BigDecimal baseToGlobalRate;

  public static final String SERIALIZED_NAME_BASE_TO_ORDER_RATE = "base_to_order_rate";
  @Json(name = SERIALIZED_NAME_BASE_TO_ORDER_RATE)
  private BigDecimal baseToOrderRate;

  public static final String SERIALIZED_NAME_BILLING_ADDRESS_ID = "billing_address_id";
  @Json(name = SERIALIZED_NAME_BILLING_ADDRESS_ID)
  private Integer billingAddressId;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @Json(name = SERIALIZED_NAME_CREATED_AT)
  private String createdAt;

  public static final String SERIALIZED_NAME_CREDITMEMO_STATUS = "creditmemo_status";
  @Json(name = SERIALIZED_NAME_CREDITMEMO_STATUS)
  private Integer creditmemoStatus;

  public static final String SERIALIZED_NAME_DISCOUNT_AMOUNT = "discount_amount";
  @Json(name = SERIALIZED_NAME_DISCOUNT_AMOUNT)
  private BigDecimal discountAmount;

  public static final String SERIALIZED_NAME_DISCOUNT_DESCRIPTION = "discount_description";
  @Json(name = SERIALIZED_NAME_DISCOUNT_DESCRIPTION)
  private String discountDescription;

  public static final String SERIALIZED_NAME_EMAIL_SENT = "email_sent";
  @Json(name = SERIALIZED_NAME_EMAIL_SENT)
  private Integer emailSent;

  public static final String SERIALIZED_NAME_ENTITY_ID = "entity_id";
  @Json(name = SERIALIZED_NAME_ENTITY_ID)
  private Integer entityId;

  public static final String SERIALIZED_NAME_GLOBAL_CURRENCY_CODE = "global_currency_code";
  @Json(name = SERIALIZED_NAME_GLOBAL_CURRENCY_CODE)
  private String globalCurrencyCode;

  public static final String SERIALIZED_NAME_GRAND_TOTAL = "grand_total";
  @Json(name = SERIALIZED_NAME_GRAND_TOTAL)
  private BigDecimal grandTotal;

  public static final String SERIALIZED_NAME_DISCOUNT_TAX_COMPENSATION_AMOUNT = "discount_tax_compensation_amount";
  @Json(name = SERIALIZED_NAME_DISCOUNT_TAX_COMPENSATION_AMOUNT)
  private BigDecimal discountTaxCompensationAmount;

  public static final String SERIALIZED_NAME_INCREMENT_ID = "increment_id";
  @Json(name = SERIALIZED_NAME_INCREMENT_ID)
  private String incrementId;

  public static final String SERIALIZED_NAME_INVOICE_ID = "invoice_id";
  @Json(name = SERIALIZED_NAME_INVOICE_ID)
  private Integer invoiceId;

  public static final String SERIALIZED_NAME_ORDER_CURRENCY_CODE = "order_currency_code";
  @Json(name = SERIALIZED_NAME_ORDER_CURRENCY_CODE)
  private String orderCurrencyCode;

  public static final String SERIALIZED_NAME_ORDER_ID = "order_id";
  @Json(name = SERIALIZED_NAME_ORDER_ID)
  private Integer orderId;

  public static final String SERIALIZED_NAME_SHIPPING_ADDRESS_ID = "shipping_address_id";
  @Json(name = SERIALIZED_NAME_SHIPPING_ADDRESS_ID)
  private Integer shippingAddressId;

  public static final String SERIALIZED_NAME_SHIPPING_AMOUNT = "shipping_amount";
  @Json(name = SERIALIZED_NAME_SHIPPING_AMOUNT)
  private BigDecimal shippingAmount;

  public static final String SERIALIZED_NAME_SHIPPING_DISCOUNT_TAX_COMPENSATION_AMOUNT = "shipping_discount_tax_compensation_amount";
  @Json(name = SERIALIZED_NAME_SHIPPING_DISCOUNT_TAX_COMPENSATION_AMOUNT)
  private BigDecimal shippingDiscountTaxCompensationAmount;

  public static final String SERIALIZED_NAME_SHIPPING_INCL_TAX = "shipping_incl_tax";
  @Json(name = SERIALIZED_NAME_SHIPPING_INCL_TAX)
  private BigDecimal shippingInclTax;

  public static final String SERIALIZED_NAME_SHIPPING_TAX_AMOUNT = "shipping_tax_amount";
  @Json(name = SERIALIZED_NAME_SHIPPING_TAX_AMOUNT)
  private BigDecimal shippingTaxAmount;

  public static final String SERIALIZED_NAME_STATE = "state";
  @Json(name = SERIALIZED_NAME_STATE)
  private Integer state;

  public static final String SERIALIZED_NAME_STORE_CURRENCY_CODE = "store_currency_code";
  @Json(name = SERIALIZED_NAME_STORE_CURRENCY_CODE)
  private String storeCurrencyCode;

  public static final String SERIALIZED_NAME_STORE_ID = "store_id";
  @Json(name = SERIALIZED_NAME_STORE_ID)
  private Integer storeId;

  public static final String SERIALIZED_NAME_STORE_TO_BASE_RATE = "store_to_base_rate";
  @Json(name = SERIALIZED_NAME_STORE_TO_BASE_RATE)
  private BigDecimal storeToBaseRate;

  public static final String SERIALIZED_NAME_STORE_TO_ORDER_RATE = "store_to_order_rate";
  @Json(name = SERIALIZED_NAME_STORE_TO_ORDER_RATE)
  private BigDecimal storeToOrderRate;

  public static final String SERIALIZED_NAME_SUBTOTAL = "subtotal";
  @Json(name = SERIALIZED_NAME_SUBTOTAL)
  private BigDecimal subtotal;

  public static final String SERIALIZED_NAME_SUBTOTAL_INCL_TAX = "subtotal_incl_tax";
  @Json(name = SERIALIZED_NAME_SUBTOTAL_INCL_TAX)
  private BigDecimal subtotalInclTax;

  public static final String SERIALIZED_NAME_TAX_AMOUNT = "tax_amount";
  @Json(name = SERIALIZED_NAME_TAX_AMOUNT)
  private BigDecimal taxAmount;

  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transaction_id";
  @Json(name = SERIALIZED_NAME_TRANSACTION_ID)
  private String transactionId;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @Json(name = SERIALIZED_NAME_UPDATED_AT)
  private String updatedAt;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @Json(name = SERIALIZED_NAME_ITEMS)
  private List<SalesDataCreditmemoItemInterface> items = new ArrayList<SalesDataCreditmemoItemInterface>();

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @Json(name = SERIALIZED_NAME_COMMENTS)
  private List<SalesDataCreditmemoCommentInterface> comments = null;

  public static final String SERIALIZED_NAME_EXTENSION_ATTRIBUTES = "extension_attributes";
  @Json(name = SERIALIZED_NAME_EXTENSION_ATTRIBUTES)
  private SalesDataCreditmemoExtensionInterface extensionAttributes;


  public SalesDataCreditmemoInterface adjustment(BigDecimal adjustment) {
    
    this.adjustment = adjustment;
    return this;
  }

   /**
   * Credit memo adjustment.
   * @return adjustment
  **/

  

  public BigDecimal getAdjustment() {
    return adjustment;
  }


  public void setAdjustment(BigDecimal adjustment) {
    this.adjustment = adjustment;
  }


  public SalesDataCreditmemoInterface adjustmentNegative(BigDecimal adjustmentNegative) {
    
    this.adjustmentNegative = adjustmentNegative;
    return this;
  }

   /**
   * Credit memo negative adjustment.
   * @return adjustmentNegative
  **/

  

  public BigDecimal getAdjustmentNegative() {
    return adjustmentNegative;
  }


  public void setAdjustmentNegative(BigDecimal adjustmentNegative) {
    this.adjustmentNegative = adjustmentNegative;
  }


  public SalesDataCreditmemoInterface adjustmentPositive(BigDecimal adjustmentPositive) {
    
    this.adjustmentPositive = adjustmentPositive;
    return this;
  }

   /**
   * Credit memo positive adjustment.
   * @return adjustmentPositive
  **/

  

  public BigDecimal getAdjustmentPositive() {
    return adjustmentPositive;
  }


  public void setAdjustmentPositive(BigDecimal adjustmentPositive) {
    this.adjustmentPositive = adjustmentPositive;
  }


  public SalesDataCreditmemoInterface baseAdjustment(BigDecimal baseAdjustment) {
    
    this.baseAdjustment = baseAdjustment;
    return this;
  }

   /**
   * Credit memo base adjustment.
   * @return baseAdjustment
  **/

  

  public BigDecimal getBaseAdjustment() {
    return baseAdjustment;
  }


  public void setBaseAdjustment(BigDecimal baseAdjustment) {
    this.baseAdjustment = baseAdjustment;
  }


  public SalesDataCreditmemoInterface baseAdjustmentNegative(BigDecimal baseAdjustmentNegative) {
    
    this.baseAdjustmentNegative = baseAdjustmentNegative;
    return this;
  }

   /**
   * Credit memo negative base adjustment.
   * @return baseAdjustmentNegative
  **/

  

  public BigDecimal getBaseAdjustmentNegative() {
    return baseAdjustmentNegative;
  }


  public void setBaseAdjustmentNegative(BigDecimal baseAdjustmentNegative) {
    this.baseAdjustmentNegative = baseAdjustmentNegative;
  }


  public SalesDataCreditmemoInterface baseAdjustmentPositive(BigDecimal baseAdjustmentPositive) {
    
    this.baseAdjustmentPositive = baseAdjustmentPositive;
    return this;
  }

   /**
   * Credit memo positive base adjustment.
   * @return baseAdjustmentPositive
  **/

  

  public BigDecimal getBaseAdjustmentPositive() {
    return baseAdjustmentPositive;
  }


  public void setBaseAdjustmentPositive(BigDecimal baseAdjustmentPositive) {
    this.baseAdjustmentPositive = baseAdjustmentPositive;
  }


  public SalesDataCreditmemoInterface baseCurrencyCode(String baseCurrencyCode) {
    
    this.baseCurrencyCode = baseCurrencyCode;
    return this;
  }

   /**
   * Credit memo base currency code.
   * @return baseCurrencyCode
  **/

  

  public String getBaseCurrencyCode() {
    return baseCurrencyCode;
  }


  public void setBaseCurrencyCode(String baseCurrencyCode) {
    this.baseCurrencyCode = baseCurrencyCode;
  }


  public SalesDataCreditmemoInterface baseDiscountAmount(BigDecimal baseDiscountAmount) {
    
    this.baseDiscountAmount = baseDiscountAmount;
    return this;
  }

   /**
   * Credit memo base discount amount.
   * @return baseDiscountAmount
  **/

  

  public BigDecimal getBaseDiscountAmount() {
    return baseDiscountAmount;
  }


  public void setBaseDiscountAmount(BigDecimal baseDiscountAmount) {
    this.baseDiscountAmount = baseDiscountAmount;
  }


  public SalesDataCreditmemoInterface baseGrandTotal(BigDecimal baseGrandTotal) {
    
    this.baseGrandTotal = baseGrandTotal;
    return this;
  }

   /**
   * Credit memo base grand total.
   * @return baseGrandTotal
  **/

  

  public BigDecimal getBaseGrandTotal() {
    return baseGrandTotal;
  }


  public void setBaseGrandTotal(BigDecimal baseGrandTotal) {
    this.baseGrandTotal = baseGrandTotal;
  }


  public SalesDataCreditmemoInterface baseDiscountTaxCompensationAmount(BigDecimal baseDiscountTaxCompensationAmount) {
    
    this.baseDiscountTaxCompensationAmount = baseDiscountTaxCompensationAmount;
    return this;
  }

   /**
   * Credit memo base discount tax compensation amount.
   * @return baseDiscountTaxCompensationAmount
  **/

  

  public BigDecimal getBaseDiscountTaxCompensationAmount() {
    return baseDiscountTaxCompensationAmount;
  }


  public void setBaseDiscountTaxCompensationAmount(BigDecimal baseDiscountTaxCompensationAmount) {
    this.baseDiscountTaxCompensationAmount = baseDiscountTaxCompensationAmount;
  }


  public SalesDataCreditmemoInterface baseShippingAmount(BigDecimal baseShippingAmount) {
    
    this.baseShippingAmount = baseShippingAmount;
    return this;
  }

   /**
   * Credit memo base shipping amount.
   * @return baseShippingAmount
  **/

  

  public BigDecimal getBaseShippingAmount() {
    return baseShippingAmount;
  }


  public void setBaseShippingAmount(BigDecimal baseShippingAmount) {
    this.baseShippingAmount = baseShippingAmount;
  }


  public SalesDataCreditmemoInterface baseShippingDiscountTaxCompensationAmnt(BigDecimal baseShippingDiscountTaxCompensationAmnt) {
    
    this.baseShippingDiscountTaxCompensationAmnt = baseShippingDiscountTaxCompensationAmnt;
    return this;
  }

   /**
   * Credit memo base shipping discount tax compensation amount.
   * @return baseShippingDiscountTaxCompensationAmnt
  **/

  

  public BigDecimal getBaseShippingDiscountTaxCompensationAmnt() {
    return baseShippingDiscountTaxCompensationAmnt;
  }


  public void setBaseShippingDiscountTaxCompensationAmnt(BigDecimal baseShippingDiscountTaxCompensationAmnt) {
    this.baseShippingDiscountTaxCompensationAmnt = baseShippingDiscountTaxCompensationAmnt;
  }


  public SalesDataCreditmemoInterface baseShippingInclTax(BigDecimal baseShippingInclTax) {
    
    this.baseShippingInclTax = baseShippingInclTax;
    return this;
  }

   /**
   * Credit memo base shipping including tax.
   * @return baseShippingInclTax
  **/

  

  public BigDecimal getBaseShippingInclTax() {
    return baseShippingInclTax;
  }


  public void setBaseShippingInclTax(BigDecimal baseShippingInclTax) {
    this.baseShippingInclTax = baseShippingInclTax;
  }


  public SalesDataCreditmemoInterface baseShippingTaxAmount(BigDecimal baseShippingTaxAmount) {
    
    this.baseShippingTaxAmount = baseShippingTaxAmount;
    return this;
  }

   /**
   * Credit memo base shipping tax amount.
   * @return baseShippingTaxAmount
  **/

  

  public BigDecimal getBaseShippingTaxAmount() {
    return baseShippingTaxAmount;
  }


  public void setBaseShippingTaxAmount(BigDecimal baseShippingTaxAmount) {
    this.baseShippingTaxAmount = baseShippingTaxAmount;
  }


  public SalesDataCreditmemoInterface baseSubtotal(BigDecimal baseSubtotal) {
    
    this.baseSubtotal = baseSubtotal;
    return this;
  }

   /**
   * Credit memo base subtotal.
   * @return baseSubtotal
  **/

  

  public BigDecimal getBaseSubtotal() {
    return baseSubtotal;
  }


  public void setBaseSubtotal(BigDecimal baseSubtotal) {
    this.baseSubtotal = baseSubtotal;
  }


  public SalesDataCreditmemoInterface baseSubtotalInclTax(BigDecimal baseSubtotalInclTax) {
    
    this.baseSubtotalInclTax = baseSubtotalInclTax;
    return this;
  }

   /**
   * Credit memo base subtotal including tax.
   * @return baseSubtotalInclTax
  **/

  

  public BigDecimal getBaseSubtotalInclTax() {
    return baseSubtotalInclTax;
  }


  public void setBaseSubtotalInclTax(BigDecimal baseSubtotalInclTax) {
    this.baseSubtotalInclTax = baseSubtotalInclTax;
  }


  public SalesDataCreditmemoInterface baseTaxAmount(BigDecimal baseTaxAmount) {
    
    this.baseTaxAmount = baseTaxAmount;
    return this;
  }

   /**
   * Credit memo base tax amount.
   * @return baseTaxAmount
  **/

  

  public BigDecimal getBaseTaxAmount() {
    return baseTaxAmount;
  }


  public void setBaseTaxAmount(BigDecimal baseTaxAmount) {
    this.baseTaxAmount = baseTaxAmount;
  }


  public SalesDataCreditmemoInterface baseToGlobalRate(BigDecimal baseToGlobalRate) {
    
    this.baseToGlobalRate = baseToGlobalRate;
    return this;
  }

   /**
   * Credit memo base-to-global rate.
   * @return baseToGlobalRate
  **/

  

  public BigDecimal getBaseToGlobalRate() {
    return baseToGlobalRate;
  }


  public void setBaseToGlobalRate(BigDecimal baseToGlobalRate) {
    this.baseToGlobalRate = baseToGlobalRate;
  }


  public SalesDataCreditmemoInterface baseToOrderRate(BigDecimal baseToOrderRate) {
    
    this.baseToOrderRate = baseToOrderRate;
    return this;
  }

   /**
   * Credit memo base-to-order rate.
   * @return baseToOrderRate
  **/

  

  public BigDecimal getBaseToOrderRate() {
    return baseToOrderRate;
  }


  public void setBaseToOrderRate(BigDecimal baseToOrderRate) {
    this.baseToOrderRate = baseToOrderRate;
  }


  public SalesDataCreditmemoInterface billingAddressId(Integer billingAddressId) {
    
    this.billingAddressId = billingAddressId;
    return this;
  }

   /**
   * Credit memo billing address ID.
   * @return billingAddressId
  **/

  

  public Integer getBillingAddressId() {
    return billingAddressId;
  }


  public void setBillingAddressId(Integer billingAddressId) {
    this.billingAddressId = billingAddressId;
  }


  public SalesDataCreditmemoInterface createdAt(String createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Credit memo created-at timestamp.
   * @return createdAt
  **/

  

  public String getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }


  public SalesDataCreditmemoInterface creditmemoStatus(Integer creditmemoStatus) {
    
    this.creditmemoStatus = creditmemoStatus;
    return this;
  }

   /**
   * Credit memo status.
   * @return creditmemoStatus
  **/

  

  public Integer getCreditmemoStatus() {
    return creditmemoStatus;
  }


  public void setCreditmemoStatus(Integer creditmemoStatus) {
    this.creditmemoStatus = creditmemoStatus;
  }


  public SalesDataCreditmemoInterface discountAmount(BigDecimal discountAmount) {
    
    this.discountAmount = discountAmount;
    return this;
  }

   /**
   * Credit memo discount amount.
   * @return discountAmount
  **/

  

  public BigDecimal getDiscountAmount() {
    return discountAmount;
  }


  public void setDiscountAmount(BigDecimal discountAmount) {
    this.discountAmount = discountAmount;
  }


  public SalesDataCreditmemoInterface discountDescription(String discountDescription) {
    
    this.discountDescription = discountDescription;
    return this;
  }

   /**
   * Credit memo discount description.
   * @return discountDescription
  **/

  

  public String getDiscountDescription() {
    return discountDescription;
  }


  public void setDiscountDescription(String discountDescription) {
    this.discountDescription = discountDescription;
  }


  public SalesDataCreditmemoInterface emailSent(Integer emailSent) {
    
    this.emailSent = emailSent;
    return this;
  }

   /**
   * Credit memo email sent flag value.
   * @return emailSent
  **/

  

  public Integer getEmailSent() {
    return emailSent;
  }


  public void setEmailSent(Integer emailSent) {
    this.emailSent = emailSent;
  }


  public SalesDataCreditmemoInterface entityId(Integer entityId) {
    
    this.entityId = entityId;
    return this;
  }

   /**
   * Credit memo ID.
   * @return entityId
  **/

  

  public Integer getEntityId() {
    return entityId;
  }


  public void setEntityId(Integer entityId) {
    this.entityId = entityId;
  }


  public SalesDataCreditmemoInterface globalCurrencyCode(String globalCurrencyCode) {
    
    this.globalCurrencyCode = globalCurrencyCode;
    return this;
  }

   /**
   * Credit memo global currency code.
   * @return globalCurrencyCode
  **/

  

  public String getGlobalCurrencyCode() {
    return globalCurrencyCode;
  }


  public void setGlobalCurrencyCode(String globalCurrencyCode) {
    this.globalCurrencyCode = globalCurrencyCode;
  }


  public SalesDataCreditmemoInterface grandTotal(BigDecimal grandTotal) {
    
    this.grandTotal = grandTotal;
    return this;
  }

   /**
   * Credit memo grand total.
   * @return grandTotal
  **/

  

  public BigDecimal getGrandTotal() {
    return grandTotal;
  }


  public void setGrandTotal(BigDecimal grandTotal) {
    this.grandTotal = grandTotal;
  }


  public SalesDataCreditmemoInterface discountTaxCompensationAmount(BigDecimal discountTaxCompensationAmount) {
    
    this.discountTaxCompensationAmount = discountTaxCompensationAmount;
    return this;
  }

   /**
   * Credit memo discount tax compensation amount.
   * @return discountTaxCompensationAmount
  **/

  

  public BigDecimal getDiscountTaxCompensationAmount() {
    return discountTaxCompensationAmount;
  }


  public void setDiscountTaxCompensationAmount(BigDecimal discountTaxCompensationAmount) {
    this.discountTaxCompensationAmount = discountTaxCompensationAmount;
  }


  public SalesDataCreditmemoInterface incrementId(String incrementId) {
    
    this.incrementId = incrementId;
    return this;
  }

   /**
   * Credit memo increment ID.
   * @return incrementId
  **/

  

  public String getIncrementId() {
    return incrementId;
  }


  public void setIncrementId(String incrementId) {
    this.incrementId = incrementId;
  }


  public SalesDataCreditmemoInterface invoiceId(Integer invoiceId) {
    
    this.invoiceId = invoiceId;
    return this;
  }

   /**
   * Credit memo invoice ID.
   * @return invoiceId
  **/

  

  public Integer getInvoiceId() {
    return invoiceId;
  }


  public void setInvoiceId(Integer invoiceId) {
    this.invoiceId = invoiceId;
  }


  public SalesDataCreditmemoInterface orderCurrencyCode(String orderCurrencyCode) {
    
    this.orderCurrencyCode = orderCurrencyCode;
    return this;
  }

   /**
   * Credit memo order currency code.
   * @return orderCurrencyCode
  **/

  

  public String getOrderCurrencyCode() {
    return orderCurrencyCode;
  }


  public void setOrderCurrencyCode(String orderCurrencyCode) {
    this.orderCurrencyCode = orderCurrencyCode;
  }


  public SalesDataCreditmemoInterface orderId(Integer orderId) {
    
    this.orderId = orderId;
    return this;
  }

   /**
   * Credit memo order ID.
   * @return orderId
  **/


  public Integer getOrderId() {
    return orderId;
  }


  public void setOrderId(Integer orderId) {
    this.orderId = orderId;
  }


  public SalesDataCreditmemoInterface shippingAddressId(Integer shippingAddressId) {
    
    this.shippingAddressId = shippingAddressId;
    return this;
  }

   /**
   * Credit memo shipping address ID.
   * @return shippingAddressId
  **/

  

  public Integer getShippingAddressId() {
    return shippingAddressId;
  }


  public void setShippingAddressId(Integer shippingAddressId) {
    this.shippingAddressId = shippingAddressId;
  }


  public SalesDataCreditmemoInterface shippingAmount(BigDecimal shippingAmount) {
    
    this.shippingAmount = shippingAmount;
    return this;
  }

   /**
   * Credit memo shipping amount.
   * @return shippingAmount
  **/

  

  public BigDecimal getShippingAmount() {
    return shippingAmount;
  }


  public void setShippingAmount(BigDecimal shippingAmount) {
    this.shippingAmount = shippingAmount;
  }


  public SalesDataCreditmemoInterface shippingDiscountTaxCompensationAmount(BigDecimal shippingDiscountTaxCompensationAmount) {
    
    this.shippingDiscountTaxCompensationAmount = shippingDiscountTaxCompensationAmount;
    return this;
  }

   /**
   * Credit memo shipping discount tax compensation amount.
   * @return shippingDiscountTaxCompensationAmount
  **/

  

  public BigDecimal getShippingDiscountTaxCompensationAmount() {
    return shippingDiscountTaxCompensationAmount;
  }


  public void setShippingDiscountTaxCompensationAmount(BigDecimal shippingDiscountTaxCompensationAmount) {
    this.shippingDiscountTaxCompensationAmount = shippingDiscountTaxCompensationAmount;
  }


  public SalesDataCreditmemoInterface shippingInclTax(BigDecimal shippingInclTax) {
    
    this.shippingInclTax = shippingInclTax;
    return this;
  }

   /**
   * Credit memo shipping including tax.
   * @return shippingInclTax
  **/

  

  public BigDecimal getShippingInclTax() {
    return shippingInclTax;
  }


  public void setShippingInclTax(BigDecimal shippingInclTax) {
    this.shippingInclTax = shippingInclTax;
  }


  public SalesDataCreditmemoInterface shippingTaxAmount(BigDecimal shippingTaxAmount) {
    
    this.shippingTaxAmount = shippingTaxAmount;
    return this;
  }

   /**
   * Credit memo shipping tax amount.
   * @return shippingTaxAmount
  **/

  

  public BigDecimal getShippingTaxAmount() {
    return shippingTaxAmount;
  }


  public void setShippingTaxAmount(BigDecimal shippingTaxAmount) {
    this.shippingTaxAmount = shippingTaxAmount;
  }


  public SalesDataCreditmemoInterface state(Integer state) {
    
    this.state = state;
    return this;
  }

   /**
   * Credit memo state.
   * @return state
  **/

  

  public Integer getState() {
    return state;
  }


  public void setState(Integer state) {
    this.state = state;
  }


  public SalesDataCreditmemoInterface storeCurrencyCode(String storeCurrencyCode) {
    
    this.storeCurrencyCode = storeCurrencyCode;
    return this;
  }

   /**
   * Credit memo store currency code.
   * @return storeCurrencyCode
  **/

  

  public String getStoreCurrencyCode() {
    return storeCurrencyCode;
  }


  public void setStoreCurrencyCode(String storeCurrencyCode) {
    this.storeCurrencyCode = storeCurrencyCode;
  }


  public SalesDataCreditmemoInterface storeId(Integer storeId) {
    
    this.storeId = storeId;
    return this;
  }

   /**
   * Credit memo store ID.
   * @return storeId
  **/

  

  public Integer getStoreId() {
    return storeId;
  }


  public void setStoreId(Integer storeId) {
    this.storeId = storeId;
  }


  public SalesDataCreditmemoInterface storeToBaseRate(BigDecimal storeToBaseRate) {
    
    this.storeToBaseRate = storeToBaseRate;
    return this;
  }

   /**
   * Credit memo store-to-base rate.
   * @return storeToBaseRate
  **/

  

  public BigDecimal getStoreToBaseRate() {
    return storeToBaseRate;
  }


  public void setStoreToBaseRate(BigDecimal storeToBaseRate) {
    this.storeToBaseRate = storeToBaseRate;
  }


  public SalesDataCreditmemoInterface storeToOrderRate(BigDecimal storeToOrderRate) {
    
    this.storeToOrderRate = storeToOrderRate;
    return this;
  }

   /**
   * Credit memo store-to-order rate.
   * @return storeToOrderRate
  **/

  

  public BigDecimal getStoreToOrderRate() {
    return storeToOrderRate;
  }


  public void setStoreToOrderRate(BigDecimal storeToOrderRate) {
    this.storeToOrderRate = storeToOrderRate;
  }


  public SalesDataCreditmemoInterface subtotal(BigDecimal subtotal) {
    
    this.subtotal = subtotal;
    return this;
  }

   /**
   * Credit memo subtotal.
   * @return subtotal
  **/

  

  public BigDecimal getSubtotal() {
    return subtotal;
  }


  public void setSubtotal(BigDecimal subtotal) {
    this.subtotal = subtotal;
  }


  public SalesDataCreditmemoInterface subtotalInclTax(BigDecimal subtotalInclTax) {
    
    this.subtotalInclTax = subtotalInclTax;
    return this;
  }

   /**
   * Credit memo subtotal including tax.
   * @return subtotalInclTax
  **/

  

  public BigDecimal getSubtotalInclTax() {
    return subtotalInclTax;
  }


  public void setSubtotalInclTax(BigDecimal subtotalInclTax) {
    this.subtotalInclTax = subtotalInclTax;
  }


  public SalesDataCreditmemoInterface taxAmount(BigDecimal taxAmount) {
    
    this.taxAmount = taxAmount;
    return this;
  }

   /**
   * Credit memo tax amount.
   * @return taxAmount
  **/

  

  public BigDecimal getTaxAmount() {
    return taxAmount;
  }


  public void setTaxAmount(BigDecimal taxAmount) {
    this.taxAmount = taxAmount;
  }


  public SalesDataCreditmemoInterface transactionId(String transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Credit memo transaction ID.
   * @return transactionId
  **/

  

  public String getTransactionId() {
    return transactionId;
  }


  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }


  public SalesDataCreditmemoInterface updatedAt(String updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Credit memo updated-at timestamp.
   * @return updatedAt
  **/

  

  public String getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  public SalesDataCreditmemoInterface items(List<SalesDataCreditmemoItemInterface> items) {
    
    this.items = items;
    return this;
  }

  public SalesDataCreditmemoInterface addItemsItem(SalesDataCreditmemoItemInterface itemsItem) {
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Array of credit memo items.
   * @return items
  **/


  public List<SalesDataCreditmemoItemInterface> getItems() {
    return items;
  }


  public void setItems(List<SalesDataCreditmemoItemInterface> items) {
    this.items = items;
  }


  public SalesDataCreditmemoInterface comments(List<SalesDataCreditmemoCommentInterface> comments) {
    
    this.comments = comments;
    return this;
  }

  public SalesDataCreditmemoInterface addCommentsItem(SalesDataCreditmemoCommentInterface commentsItem) {
    if (this.comments == null) {
      this.comments = new ArrayList<SalesDataCreditmemoCommentInterface>();
    }
    this.comments.add(commentsItem);
    return this;
  }

   /**
   * Array of any credit memo comments. Otherwise, null.
   * @return comments
  **/

  

  public List<SalesDataCreditmemoCommentInterface> getComments() {
    return comments;
  }


  public void setComments(List<SalesDataCreditmemoCommentInterface> comments) {
    this.comments = comments;
  }


  public SalesDataCreditmemoInterface extensionAttributes(SalesDataCreditmemoExtensionInterface extensionAttributes) {
    
    this.extensionAttributes = extensionAttributes;
    return this;
  }

   /**
   * Get extensionAttributes
   * @return extensionAttributes
  **/

  

  public SalesDataCreditmemoExtensionInterface getExtensionAttributes() {
    return extensionAttributes;
  }


  public void setExtensionAttributes(SalesDataCreditmemoExtensionInterface extensionAttributes) {
    this.extensionAttributes = extensionAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalesDataCreditmemoInterface salesDataCreditmemoInterface = (SalesDataCreditmemoInterface) o;
    return Objects.equals(this.adjustment, salesDataCreditmemoInterface.adjustment) &&
        Objects.equals(this.adjustmentNegative, salesDataCreditmemoInterface.adjustmentNegative) &&
        Objects.equals(this.adjustmentPositive, salesDataCreditmemoInterface.adjustmentPositive) &&
        Objects.equals(this.baseAdjustment, salesDataCreditmemoInterface.baseAdjustment) &&
        Objects.equals(this.baseAdjustmentNegative, salesDataCreditmemoInterface.baseAdjustmentNegative) &&
        Objects.equals(this.baseAdjustmentPositive, salesDataCreditmemoInterface.baseAdjustmentPositive) &&
        Objects.equals(this.baseCurrencyCode, salesDataCreditmemoInterface.baseCurrencyCode) &&
        Objects.equals(this.baseDiscountAmount, salesDataCreditmemoInterface.baseDiscountAmount) &&
        Objects.equals(this.baseGrandTotal, salesDataCreditmemoInterface.baseGrandTotal) &&
        Objects.equals(this.baseDiscountTaxCompensationAmount, salesDataCreditmemoInterface.baseDiscountTaxCompensationAmount) &&
        Objects.equals(this.baseShippingAmount, salesDataCreditmemoInterface.baseShippingAmount) &&
        Objects.equals(this.baseShippingDiscountTaxCompensationAmnt, salesDataCreditmemoInterface.baseShippingDiscountTaxCompensationAmnt) &&
        Objects.equals(this.baseShippingInclTax, salesDataCreditmemoInterface.baseShippingInclTax) &&
        Objects.equals(this.baseShippingTaxAmount, salesDataCreditmemoInterface.baseShippingTaxAmount) &&
        Objects.equals(this.baseSubtotal, salesDataCreditmemoInterface.baseSubtotal) &&
        Objects.equals(this.baseSubtotalInclTax, salesDataCreditmemoInterface.baseSubtotalInclTax) &&
        Objects.equals(this.baseTaxAmount, salesDataCreditmemoInterface.baseTaxAmount) &&
        Objects.equals(this.baseToGlobalRate, salesDataCreditmemoInterface.baseToGlobalRate) &&
        Objects.equals(this.baseToOrderRate, salesDataCreditmemoInterface.baseToOrderRate) &&
        Objects.equals(this.billingAddressId, salesDataCreditmemoInterface.billingAddressId) &&
        Objects.equals(this.createdAt, salesDataCreditmemoInterface.createdAt) &&
        Objects.equals(this.creditmemoStatus, salesDataCreditmemoInterface.creditmemoStatus) &&
        Objects.equals(this.discountAmount, salesDataCreditmemoInterface.discountAmount) &&
        Objects.equals(this.discountDescription, salesDataCreditmemoInterface.discountDescription) &&
        Objects.equals(this.emailSent, salesDataCreditmemoInterface.emailSent) &&
        Objects.equals(this.entityId, salesDataCreditmemoInterface.entityId) &&
        Objects.equals(this.globalCurrencyCode, salesDataCreditmemoInterface.globalCurrencyCode) &&
        Objects.equals(this.grandTotal, salesDataCreditmemoInterface.grandTotal) &&
        Objects.equals(this.discountTaxCompensationAmount, salesDataCreditmemoInterface.discountTaxCompensationAmount) &&
        Objects.equals(this.incrementId, salesDataCreditmemoInterface.incrementId) &&
        Objects.equals(this.invoiceId, salesDataCreditmemoInterface.invoiceId) &&
        Objects.equals(this.orderCurrencyCode, salesDataCreditmemoInterface.orderCurrencyCode) &&
        Objects.equals(this.orderId, salesDataCreditmemoInterface.orderId) &&
        Objects.equals(this.shippingAddressId, salesDataCreditmemoInterface.shippingAddressId) &&
        Objects.equals(this.shippingAmount, salesDataCreditmemoInterface.shippingAmount) &&
        Objects.equals(this.shippingDiscountTaxCompensationAmount, salesDataCreditmemoInterface.shippingDiscountTaxCompensationAmount) &&
        Objects.equals(this.shippingInclTax, salesDataCreditmemoInterface.shippingInclTax) &&
        Objects.equals(this.shippingTaxAmount, salesDataCreditmemoInterface.shippingTaxAmount) &&
        Objects.equals(this.state, salesDataCreditmemoInterface.state) &&
        Objects.equals(this.storeCurrencyCode, salesDataCreditmemoInterface.storeCurrencyCode) &&
        Objects.equals(this.storeId, salesDataCreditmemoInterface.storeId) &&
        Objects.equals(this.storeToBaseRate, salesDataCreditmemoInterface.storeToBaseRate) &&
        Objects.equals(this.storeToOrderRate, salesDataCreditmemoInterface.storeToOrderRate) &&
        Objects.equals(this.subtotal, salesDataCreditmemoInterface.subtotal) &&
        Objects.equals(this.subtotalInclTax, salesDataCreditmemoInterface.subtotalInclTax) &&
        Objects.equals(this.taxAmount, salesDataCreditmemoInterface.taxAmount) &&
        Objects.equals(this.transactionId, salesDataCreditmemoInterface.transactionId) &&
        Objects.equals(this.updatedAt, salesDataCreditmemoInterface.updatedAt) &&
        Objects.equals(this.items, salesDataCreditmemoInterface.items) &&
        Objects.equals(this.comments, salesDataCreditmemoInterface.comments) &&
        Objects.equals(this.extensionAttributes, salesDataCreditmemoInterface.extensionAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adjustment, adjustmentNegative, adjustmentPositive, baseAdjustment, baseAdjustmentNegative, baseAdjustmentPositive, baseCurrencyCode, baseDiscountAmount, baseGrandTotal, baseDiscountTaxCompensationAmount, baseShippingAmount, baseShippingDiscountTaxCompensationAmnt, baseShippingInclTax, baseShippingTaxAmount, baseSubtotal, baseSubtotalInclTax, baseTaxAmount, baseToGlobalRate, baseToOrderRate, billingAddressId, createdAt, creditmemoStatus, discountAmount, discountDescription, emailSent, entityId, globalCurrencyCode, grandTotal, discountTaxCompensationAmount, incrementId, invoiceId, orderCurrencyCode, orderId, shippingAddressId, shippingAmount, shippingDiscountTaxCompensationAmount, shippingInclTax, shippingTaxAmount, state, storeCurrencyCode, storeId, storeToBaseRate, storeToOrderRate, subtotal, subtotalInclTax, taxAmount, transactionId, updatedAt, items, comments, extensionAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalesDataCreditmemoInterface {\n");
    sb.append("    adjustment: ").append(toIndentedString(adjustment)).append("\n");
    sb.append("    adjustmentNegative: ").append(toIndentedString(adjustmentNegative)).append("\n");
    sb.append("    adjustmentPositive: ").append(toIndentedString(adjustmentPositive)).append("\n");
    sb.append("    baseAdjustment: ").append(toIndentedString(baseAdjustment)).append("\n");
    sb.append("    baseAdjustmentNegative: ").append(toIndentedString(baseAdjustmentNegative)).append("\n");
    sb.append("    baseAdjustmentPositive: ").append(toIndentedString(baseAdjustmentPositive)).append("\n");
    sb.append("    baseCurrencyCode: ").append(toIndentedString(baseCurrencyCode)).append("\n");
    sb.append("    baseDiscountAmount: ").append(toIndentedString(baseDiscountAmount)).append("\n");
    sb.append("    baseGrandTotal: ").append(toIndentedString(baseGrandTotal)).append("\n");
    sb.append("    baseDiscountTaxCompensationAmount: ").append(toIndentedString(baseDiscountTaxCompensationAmount)).append("\n");
    sb.append("    baseShippingAmount: ").append(toIndentedString(baseShippingAmount)).append("\n");
    sb.append("    baseShippingDiscountTaxCompensationAmnt: ").append(toIndentedString(baseShippingDiscountTaxCompensationAmnt)).append("\n");
    sb.append("    baseShippingInclTax: ").append(toIndentedString(baseShippingInclTax)).append("\n");
    sb.append("    baseShippingTaxAmount: ").append(toIndentedString(baseShippingTaxAmount)).append("\n");
    sb.append("    baseSubtotal: ").append(toIndentedString(baseSubtotal)).append("\n");
    sb.append("    baseSubtotalInclTax: ").append(toIndentedString(baseSubtotalInclTax)).append("\n");
    sb.append("    baseTaxAmount: ").append(toIndentedString(baseTaxAmount)).append("\n");
    sb.append("    baseToGlobalRate: ").append(toIndentedString(baseToGlobalRate)).append("\n");
    sb.append("    baseToOrderRate: ").append(toIndentedString(baseToOrderRate)).append("\n");
    sb.append("    billingAddressId: ").append(toIndentedString(billingAddressId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    creditmemoStatus: ").append(toIndentedString(creditmemoStatus)).append("\n");
    sb.append("    discountAmount: ").append(toIndentedString(discountAmount)).append("\n");
    sb.append("    discountDescription: ").append(toIndentedString(discountDescription)).append("\n");
    sb.append("    emailSent: ").append(toIndentedString(emailSent)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    globalCurrencyCode: ").append(toIndentedString(globalCurrencyCode)).append("\n");
    sb.append("    grandTotal: ").append(toIndentedString(grandTotal)).append("\n");
    sb.append("    discountTaxCompensationAmount: ").append(toIndentedString(discountTaxCompensationAmount)).append("\n");
    sb.append("    incrementId: ").append(toIndentedString(incrementId)).append("\n");
    sb.append("    invoiceId: ").append(toIndentedString(invoiceId)).append("\n");
    sb.append("    orderCurrencyCode: ").append(toIndentedString(orderCurrencyCode)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    shippingAddressId: ").append(toIndentedString(shippingAddressId)).append("\n");
    sb.append("    shippingAmount: ").append(toIndentedString(shippingAmount)).append("\n");
    sb.append("    shippingDiscountTaxCompensationAmount: ").append(toIndentedString(shippingDiscountTaxCompensationAmount)).append("\n");
    sb.append("    shippingInclTax: ").append(toIndentedString(shippingInclTax)).append("\n");
    sb.append("    shippingTaxAmount: ").append(toIndentedString(shippingTaxAmount)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    storeCurrencyCode: ").append(toIndentedString(storeCurrencyCode)).append("\n");
    sb.append("    storeId: ").append(toIndentedString(storeId)).append("\n");
    sb.append("    storeToBaseRate: ").append(toIndentedString(storeToBaseRate)).append("\n");
    sb.append("    storeToOrderRate: ").append(toIndentedString(storeToOrderRate)).append("\n");
    sb.append("    subtotal: ").append(toIndentedString(subtotal)).append("\n");
    sb.append("    subtotalInclTax: ").append(toIndentedString(subtotalInclTax)).append("\n");
    sb.append("    taxAmount: ").append(toIndentedString(taxAmount)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    extensionAttributes: ").append(toIndentedString(extensionAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

