/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;


import java.math.BigDecimal;

/**
 * Credit memo item interface. After a customer places and pays for an order and an invoice has been issued, the merchant can create a credit memo to refund all or part of the amount paid for any returned or undelivered items. The memo restores funds to the customer account so that the customer can make future purchases. A credit memo item is an invoiced item for which a merchant creates a credit memo.
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class SalesDataCreditmemoItemInterface {
  public static final String SERIALIZED_NAME_ADDITIONAL_DATA = "additional_data";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_DATA)
  private String additionalData;

  public static final String SERIALIZED_NAME_BASE_COST = "base_cost";
  @SerializedName(SERIALIZED_NAME_BASE_COST)
  private BigDecimal baseCost;

  public static final String SERIALIZED_NAME_BASE_DISCOUNT_AMOUNT = "base_discount_amount";
  @SerializedName(SERIALIZED_NAME_BASE_DISCOUNT_AMOUNT)
  private BigDecimal baseDiscountAmount;

  public static final String SERIALIZED_NAME_BASE_DISCOUNT_TAX_COMPENSATION_AMOUNT = "base_discount_tax_compensation_amount";
  @SerializedName(SERIALIZED_NAME_BASE_DISCOUNT_TAX_COMPENSATION_AMOUNT)
  private BigDecimal baseDiscountTaxCompensationAmount;

  public static final String SERIALIZED_NAME_BASE_PRICE = "base_price";
  @SerializedName(SERIALIZED_NAME_BASE_PRICE)
  private BigDecimal basePrice;

  public static final String SERIALIZED_NAME_BASE_PRICE_INCL_TAX = "base_price_incl_tax";
  @SerializedName(SERIALIZED_NAME_BASE_PRICE_INCL_TAX)
  private BigDecimal basePriceInclTax;

  public static final String SERIALIZED_NAME_BASE_ROW_TOTAL = "base_row_total";
  @SerializedName(SERIALIZED_NAME_BASE_ROW_TOTAL)
  private BigDecimal baseRowTotal;

  public static final String SERIALIZED_NAME_BASE_ROW_TOTAL_INCL_TAX = "base_row_total_incl_tax";
  @SerializedName(SERIALIZED_NAME_BASE_ROW_TOTAL_INCL_TAX)
  private BigDecimal baseRowTotalInclTax;

  public static final String SERIALIZED_NAME_BASE_TAX_AMOUNT = "base_tax_amount";
  @SerializedName(SERIALIZED_NAME_BASE_TAX_AMOUNT)
  private BigDecimal baseTaxAmount;

  public static final String SERIALIZED_NAME_BASE_WEEE_TAX_APPLIED_AMOUNT = "base_weee_tax_applied_amount";
  @SerializedName(SERIALIZED_NAME_BASE_WEEE_TAX_APPLIED_AMOUNT)
  private BigDecimal baseWeeeTaxAppliedAmount;

  public static final String SERIALIZED_NAME_BASE_WEEE_TAX_APPLIED_ROW_AMNT = "base_weee_tax_applied_row_amnt";
  @SerializedName(SERIALIZED_NAME_BASE_WEEE_TAX_APPLIED_ROW_AMNT)
  private BigDecimal baseWeeeTaxAppliedRowAmnt;

  public static final String SERIALIZED_NAME_BASE_WEEE_TAX_DISPOSITION = "base_weee_tax_disposition";
  @SerializedName(SERIALIZED_NAME_BASE_WEEE_TAX_DISPOSITION)
  private BigDecimal baseWeeeTaxDisposition;

  public static final String SERIALIZED_NAME_BASE_WEEE_TAX_ROW_DISPOSITION = "base_weee_tax_row_disposition";
  @SerializedName(SERIALIZED_NAME_BASE_WEEE_TAX_ROW_DISPOSITION)
  private BigDecimal baseWeeeTaxRowDisposition;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_DISCOUNT_AMOUNT = "discount_amount";
  @SerializedName(SERIALIZED_NAME_DISCOUNT_AMOUNT)
  private BigDecimal discountAmount;

  public static final String SERIALIZED_NAME_ENTITY_ID = "entity_id";
  @SerializedName(SERIALIZED_NAME_ENTITY_ID)
  private Integer entityId;

  public static final String SERIALIZED_NAME_DISCOUNT_TAX_COMPENSATION_AMOUNT = "discount_tax_compensation_amount";
  @SerializedName(SERIALIZED_NAME_DISCOUNT_TAX_COMPENSATION_AMOUNT)
  private BigDecimal discountTaxCompensationAmount;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ORDER_ITEM_ID = "order_item_id";
  @SerializedName(SERIALIZED_NAME_ORDER_ITEM_ID)
  private Integer orderItemId;

  public static final String SERIALIZED_NAME_PARENT_ID = "parent_id";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  private Integer parentId;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private BigDecimal price;

  public static final String SERIALIZED_NAME_PRICE_INCL_TAX = "price_incl_tax";
  @SerializedName(SERIALIZED_NAME_PRICE_INCL_TAX)
  private BigDecimal priceInclTax;

  public static final String SERIALIZED_NAME_PRODUCT_ID = "product_id";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  private Integer productId;

  public static final String SERIALIZED_NAME_QTY = "qty";
  @SerializedName(SERIALIZED_NAME_QTY)
  private BigDecimal qty;

  public static final String SERIALIZED_NAME_ROW_TOTAL = "row_total";
  @SerializedName(SERIALIZED_NAME_ROW_TOTAL)
  private BigDecimal rowTotal;

  public static final String SERIALIZED_NAME_ROW_TOTAL_INCL_TAX = "row_total_incl_tax";
  @SerializedName(SERIALIZED_NAME_ROW_TOTAL_INCL_TAX)
  private BigDecimal rowTotalInclTax;

  public static final String SERIALIZED_NAME_SKU = "sku";
  @SerializedName(SERIALIZED_NAME_SKU)
  private String sku;

  public static final String SERIALIZED_NAME_TAX_AMOUNT = "tax_amount";
  @SerializedName(SERIALIZED_NAME_TAX_AMOUNT)
  private BigDecimal taxAmount;

  public static final String SERIALIZED_NAME_WEEE_TAX_APPLIED = "weee_tax_applied";
  @SerializedName(SERIALIZED_NAME_WEEE_TAX_APPLIED)
  private String weeeTaxApplied;

  public static final String SERIALIZED_NAME_WEEE_TAX_APPLIED_AMOUNT = "weee_tax_applied_amount";
  @SerializedName(SERIALIZED_NAME_WEEE_TAX_APPLIED_AMOUNT)
  private BigDecimal weeeTaxAppliedAmount;

  public static final String SERIALIZED_NAME_WEEE_TAX_APPLIED_ROW_AMOUNT = "weee_tax_applied_row_amount";
  @SerializedName(SERIALIZED_NAME_WEEE_TAX_APPLIED_ROW_AMOUNT)
  private BigDecimal weeeTaxAppliedRowAmount;

  public static final String SERIALIZED_NAME_WEEE_TAX_DISPOSITION = "weee_tax_disposition";
  @SerializedName(SERIALIZED_NAME_WEEE_TAX_DISPOSITION)
  private BigDecimal weeeTaxDisposition;

  public static final String SERIALIZED_NAME_WEEE_TAX_ROW_DISPOSITION = "weee_tax_row_disposition";
  @SerializedName(SERIALIZED_NAME_WEEE_TAX_ROW_DISPOSITION)
  private BigDecimal weeeTaxRowDisposition;

  public static final String SERIALIZED_NAME_EXTENSION_ATTRIBUTES = "extension_attributes";
  @SerializedName(SERIALIZED_NAME_EXTENSION_ATTRIBUTES)
  private Object extensionAttributes;


  public SalesDataCreditmemoItemInterface additionalData(String additionalData) {
    
    this.additionalData = additionalData;
    return this;
  }

   /**
   * Additional data.
   * @return additionalData
  **/
  


  public String getAdditionalData() {
    return additionalData;
  }


  public void setAdditionalData(String additionalData) {
    this.additionalData = additionalData;
  }


  public SalesDataCreditmemoItemInterface baseCost(BigDecimal baseCost) {
    
    this.baseCost = baseCost;
    return this;
  }

   /**
   * The base cost for a credit memo item.
   * @return baseCost
  **/
  

  public BigDecimal getBaseCost() {
    return baseCost;
  }


  public void setBaseCost(BigDecimal baseCost) {
    this.baseCost = baseCost;
  }


  public SalesDataCreditmemoItemInterface baseDiscountAmount(BigDecimal baseDiscountAmount) {
    
    this.baseDiscountAmount = baseDiscountAmount;
    return this;
  }

   /**
   * The base discount amount for a credit memo item.
   * @return baseDiscountAmount
  **/
  


  public BigDecimal getBaseDiscountAmount() {
    return baseDiscountAmount;
  }


  public void setBaseDiscountAmount(BigDecimal baseDiscountAmount) {
    this.baseDiscountAmount = baseDiscountAmount;
  }


  public SalesDataCreditmemoItemInterface baseDiscountTaxCompensationAmount(BigDecimal baseDiscountTaxCompensationAmount) {
    
    this.baseDiscountTaxCompensationAmount = baseDiscountTaxCompensationAmount;
    return this;
  }

   /**
   * The base discount tax compensation amount for a credit memo item.
   * @return baseDiscountTaxCompensationAmount
  **/
  


  public BigDecimal getBaseDiscountTaxCompensationAmount() {
    return baseDiscountTaxCompensationAmount;
  }


  public void setBaseDiscountTaxCompensationAmount(BigDecimal baseDiscountTaxCompensationAmount) {
    this.baseDiscountTaxCompensationAmount = baseDiscountTaxCompensationAmount;
  }


  public SalesDataCreditmemoItemInterface basePrice(BigDecimal basePrice) {
    
    this.basePrice = basePrice;
    return this;
  }

   /**
   * The base price for a credit memo item.
   * @return basePrice
  **/
  

  public BigDecimal getBasePrice() {
    return basePrice;
  }


  public void setBasePrice(BigDecimal basePrice) {
    this.basePrice = basePrice;
  }


  public SalesDataCreditmemoItemInterface basePriceInclTax(BigDecimal basePriceInclTax) {
    
    this.basePriceInclTax = basePriceInclTax;
    return this;
  }

   /**
   * Base price including tax.
   * @return basePriceInclTax
  **/
  


  public BigDecimal getBasePriceInclTax() {
    return basePriceInclTax;
  }


  public void setBasePriceInclTax(BigDecimal basePriceInclTax) {
    this.basePriceInclTax = basePriceInclTax;
  }


  public SalesDataCreditmemoItemInterface baseRowTotal(BigDecimal baseRowTotal) {
    
    this.baseRowTotal = baseRowTotal;
    return this;
  }

   /**
   * Base row total.
   * @return baseRowTotal
  **/
  


  public BigDecimal getBaseRowTotal() {
    return baseRowTotal;
  }


  public void setBaseRowTotal(BigDecimal baseRowTotal) {
    this.baseRowTotal = baseRowTotal;
  }


  public SalesDataCreditmemoItemInterface baseRowTotalInclTax(BigDecimal baseRowTotalInclTax) {
    
    this.baseRowTotalInclTax = baseRowTotalInclTax;
    return this;
  }

   /**
   * Base row total including tax.
   * @return baseRowTotalInclTax
  **/
  


  public BigDecimal getBaseRowTotalInclTax() {
    return baseRowTotalInclTax;
  }


  public void setBaseRowTotalInclTax(BigDecimal baseRowTotalInclTax) {
    this.baseRowTotalInclTax = baseRowTotalInclTax;
  }


  public SalesDataCreditmemoItemInterface baseTaxAmount(BigDecimal baseTaxAmount) {
    
    this.baseTaxAmount = baseTaxAmount;
    return this;
  }

   /**
   * Base tax amount.
   * @return baseTaxAmount
  **/
  


  public BigDecimal getBaseTaxAmount() {
    return baseTaxAmount;
  }


  public void setBaseTaxAmount(BigDecimal baseTaxAmount) {
    this.baseTaxAmount = baseTaxAmount;
  }


  public SalesDataCreditmemoItemInterface baseWeeeTaxAppliedAmount(BigDecimal baseWeeeTaxAppliedAmount) {
    
    this.baseWeeeTaxAppliedAmount = baseWeeeTaxAppliedAmount;
    return this;
  }

   /**
   * Base WEEE tax applied amount.
   * @return baseWeeeTaxAppliedAmount
  **/
  


  public BigDecimal getBaseWeeeTaxAppliedAmount() {
    return baseWeeeTaxAppliedAmount;
  }


  public void setBaseWeeeTaxAppliedAmount(BigDecimal baseWeeeTaxAppliedAmount) {
    this.baseWeeeTaxAppliedAmount = baseWeeeTaxAppliedAmount;
  }


  public SalesDataCreditmemoItemInterface baseWeeeTaxAppliedRowAmnt(BigDecimal baseWeeeTaxAppliedRowAmnt) {
    
    this.baseWeeeTaxAppliedRowAmnt = baseWeeeTaxAppliedRowAmnt;
    return this;
  }

   /**
   * Base WEEE tax applied row amount.
   * @return baseWeeeTaxAppliedRowAmnt
  **/
  


  public BigDecimal getBaseWeeeTaxAppliedRowAmnt() {
    return baseWeeeTaxAppliedRowAmnt;
  }


  public void setBaseWeeeTaxAppliedRowAmnt(BigDecimal baseWeeeTaxAppliedRowAmnt) {
    this.baseWeeeTaxAppliedRowAmnt = baseWeeeTaxAppliedRowAmnt;
  }


  public SalesDataCreditmemoItemInterface baseWeeeTaxDisposition(BigDecimal baseWeeeTaxDisposition) {
    
    this.baseWeeeTaxDisposition = baseWeeeTaxDisposition;
    return this;
  }

   /**
   * Base WEEE tax disposition.
   * @return baseWeeeTaxDisposition
  **/
  


  public BigDecimal getBaseWeeeTaxDisposition() {
    return baseWeeeTaxDisposition;
  }


  public void setBaseWeeeTaxDisposition(BigDecimal baseWeeeTaxDisposition) {
    this.baseWeeeTaxDisposition = baseWeeeTaxDisposition;
  }


  public SalesDataCreditmemoItemInterface baseWeeeTaxRowDisposition(BigDecimal baseWeeeTaxRowDisposition) {
    
    this.baseWeeeTaxRowDisposition = baseWeeeTaxRowDisposition;
    return this;
  }

   /**
   * Base WEEE tax row disposition.
   * @return baseWeeeTaxRowDisposition
  **/
  


  public BigDecimal getBaseWeeeTaxRowDisposition() {
    return baseWeeeTaxRowDisposition;
  }


  public void setBaseWeeeTaxRowDisposition(BigDecimal baseWeeeTaxRowDisposition) {
    this.baseWeeeTaxRowDisposition = baseWeeeTaxRowDisposition;
  }


  public SalesDataCreditmemoItemInterface description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Description.
   * @return description
  **/
  


  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public SalesDataCreditmemoItemInterface discountAmount(BigDecimal discountAmount) {
    
    this.discountAmount = discountAmount;
    return this;
  }

   /**
   * Discount amount.
   * @return discountAmount
  **/
  


  public BigDecimal getDiscountAmount() {
    return discountAmount;
  }


  public void setDiscountAmount(BigDecimal discountAmount) {
    this.discountAmount = discountAmount;
  }


  public SalesDataCreditmemoItemInterface entityId(Integer entityId) {
    
    this.entityId = entityId;
    return this;
  }

   /**
   * Credit memo item ID.
   * @return entityId
  **/
  

  public Integer getEntityId() {
    return entityId;
  }


  public void setEntityId(Integer entityId) {
    this.entityId = entityId;
  }


  public SalesDataCreditmemoItemInterface discountTaxCompensationAmount(BigDecimal discountTaxCompensationAmount) {
    
    this.discountTaxCompensationAmount = discountTaxCompensationAmount;
    return this;
  }

   /**
   * Discount tax compensation amount.
   * @return discountTaxCompensationAmount
  **/
  


  public BigDecimal getDiscountTaxCompensationAmount() {
    return discountTaxCompensationAmount;
  }


  public void setDiscountTaxCompensationAmount(BigDecimal discountTaxCompensationAmount) {
    this.discountTaxCompensationAmount = discountTaxCompensationAmount;
  }


  public SalesDataCreditmemoItemInterface name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name.
   * @return name
  **/
  


  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public SalesDataCreditmemoItemInterface orderItemId(Integer orderItemId) {
    
    this.orderItemId = orderItemId;
    return this;
  }

   /**
   * Order item ID.
   * @return orderItemId
  **/
  

  public Integer getOrderItemId() {
    return orderItemId;
  }


  public void setOrderItemId(Integer orderItemId) {
    this.orderItemId = orderItemId;
  }


  public SalesDataCreditmemoItemInterface parentId(Integer parentId) {
    
    this.parentId = parentId;
    return this;
  }

   /**
   * Parent ID.
   * @return parentId
  **/
  


  public Integer getParentId() {
    return parentId;
  }


  public void setParentId(Integer parentId) {
    this.parentId = parentId;
  }


  public SalesDataCreditmemoItemInterface price(BigDecimal price) {
    
    this.price = price;
    return this;
  }

   /**
   * Price.
   * @return price
  **/
  


  public BigDecimal getPrice() {
    return price;
  }


  public void setPrice(BigDecimal price) {
    this.price = price;
  }


  public SalesDataCreditmemoItemInterface priceInclTax(BigDecimal priceInclTax) {
    
    this.priceInclTax = priceInclTax;
    return this;
  }

   /**
   * Price including tax.
   * @return priceInclTax
  **/
  


  public BigDecimal getPriceInclTax() {
    return priceInclTax;
  }


  public void setPriceInclTax(BigDecimal priceInclTax) {
    this.priceInclTax = priceInclTax;
  }


  public SalesDataCreditmemoItemInterface productId(Integer productId) {
    
    this.productId = productId;
    return this;
  }

   /**
   * Product ID.
   * @return productId
  **/
  


  public Integer getProductId() {
    return productId;
  }


  public void setProductId(Integer productId) {
    this.productId = productId;
  }


  public SalesDataCreditmemoItemInterface qty(BigDecimal qty) {
    
    this.qty = qty;
    return this;
  }

   /**
   * Quantity.
   * @return qty
  **/
  

  public BigDecimal getQty() {
    return qty;
  }


  public void setQty(BigDecimal qty) {
    this.qty = qty;
  }


  public SalesDataCreditmemoItemInterface rowTotal(BigDecimal rowTotal) {
    
    this.rowTotal = rowTotal;
    return this;
  }

   /**
   * Row total.
   * @return rowTotal
  **/
  


  public BigDecimal getRowTotal() {
    return rowTotal;
  }


  public void setRowTotal(BigDecimal rowTotal) {
    this.rowTotal = rowTotal;
  }


  public SalesDataCreditmemoItemInterface rowTotalInclTax(BigDecimal rowTotalInclTax) {
    
    this.rowTotalInclTax = rowTotalInclTax;
    return this;
  }

   /**
   * Row total including tax.
   * @return rowTotalInclTax
  **/
  


  public BigDecimal getRowTotalInclTax() {
    return rowTotalInclTax;
  }


  public void setRowTotalInclTax(BigDecimal rowTotalInclTax) {
    this.rowTotalInclTax = rowTotalInclTax;
  }


  public SalesDataCreditmemoItemInterface sku(String sku) {
    
    this.sku = sku;
    return this;
  }

   /**
   * SKU.
   * @return sku
  **/
  


  public String getSku() {
    return sku;
  }


  public void setSku(String sku) {
    this.sku = sku;
  }


  public SalesDataCreditmemoItemInterface taxAmount(BigDecimal taxAmount) {
    
    this.taxAmount = taxAmount;
    return this;
  }

   /**
   * Tax amount.
   * @return taxAmount
  **/
  


  public BigDecimal getTaxAmount() {
    return taxAmount;
  }


  public void setTaxAmount(BigDecimal taxAmount) {
    this.taxAmount = taxAmount;
  }


  public SalesDataCreditmemoItemInterface weeeTaxApplied(String weeeTaxApplied) {
    
    this.weeeTaxApplied = weeeTaxApplied;
    return this;
  }

   /**
   * WEEE tax applied.
   * @return weeeTaxApplied
  **/
  


  public String getWeeeTaxApplied() {
    return weeeTaxApplied;
  }


  public void setWeeeTaxApplied(String weeeTaxApplied) {
    this.weeeTaxApplied = weeeTaxApplied;
  }


  public SalesDataCreditmemoItemInterface weeeTaxAppliedAmount(BigDecimal weeeTaxAppliedAmount) {
    
    this.weeeTaxAppliedAmount = weeeTaxAppliedAmount;
    return this;
  }

   /**
   * WEEE tax applied amount.
   * @return weeeTaxAppliedAmount
  **/
  


  public BigDecimal getWeeeTaxAppliedAmount() {
    return weeeTaxAppliedAmount;
  }


  public void setWeeeTaxAppliedAmount(BigDecimal weeeTaxAppliedAmount) {
    this.weeeTaxAppliedAmount = weeeTaxAppliedAmount;
  }


  public SalesDataCreditmemoItemInterface weeeTaxAppliedRowAmount(BigDecimal weeeTaxAppliedRowAmount) {
    
    this.weeeTaxAppliedRowAmount = weeeTaxAppliedRowAmount;
    return this;
  }

   /**
   * WEEE tax applied row amount.
   * @return weeeTaxAppliedRowAmount
  **/
  


  public BigDecimal getWeeeTaxAppliedRowAmount() {
    return weeeTaxAppliedRowAmount;
  }


  public void setWeeeTaxAppliedRowAmount(BigDecimal weeeTaxAppliedRowAmount) {
    this.weeeTaxAppliedRowAmount = weeeTaxAppliedRowAmount;
  }


  public SalesDataCreditmemoItemInterface weeeTaxDisposition(BigDecimal weeeTaxDisposition) {
    
    this.weeeTaxDisposition = weeeTaxDisposition;
    return this;
  }

   /**
   * WEEE tax disposition.
   * @return weeeTaxDisposition
  **/
  


  public BigDecimal getWeeeTaxDisposition() {
    return weeeTaxDisposition;
  }


  public void setWeeeTaxDisposition(BigDecimal weeeTaxDisposition) {
    this.weeeTaxDisposition = weeeTaxDisposition;
  }


  public SalesDataCreditmemoItemInterface weeeTaxRowDisposition(BigDecimal weeeTaxRowDisposition) {
    
    this.weeeTaxRowDisposition = weeeTaxRowDisposition;
    return this;
  }

   /**
   * WEEE tax row disposition.
   * @return weeeTaxRowDisposition
  **/
  


  public BigDecimal getWeeeTaxRowDisposition() {
    return weeeTaxRowDisposition;
  }


  public void setWeeeTaxRowDisposition(BigDecimal weeeTaxRowDisposition) {
    this.weeeTaxRowDisposition = weeeTaxRowDisposition;
  }


  public SalesDataCreditmemoItemInterface extensionAttributes(Object extensionAttributes) {
    
    this.extensionAttributes = extensionAttributes;
    return this;
  }

   /**
   * ExtensionInterface class for @see \\Magento\\Sales\\Api\\Data\\CreditmemoItemInterface
   * @return extensionAttributes
  **/
  


  public Object getExtensionAttributes() {
    return extensionAttributes;
  }


  public void setExtensionAttributes(Object extensionAttributes) {
    this.extensionAttributes = extensionAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalesDataCreditmemoItemInterface salesDataCreditmemoItemInterface = (SalesDataCreditmemoItemInterface) o;
    return Objects.equals(this.additionalData, salesDataCreditmemoItemInterface.additionalData) &&
        Objects.equals(this.baseCost, salesDataCreditmemoItemInterface.baseCost) &&
        Objects.equals(this.baseDiscountAmount, salesDataCreditmemoItemInterface.baseDiscountAmount) &&
        Objects.equals(this.baseDiscountTaxCompensationAmount, salesDataCreditmemoItemInterface.baseDiscountTaxCompensationAmount) &&
        Objects.equals(this.basePrice, salesDataCreditmemoItemInterface.basePrice) &&
        Objects.equals(this.basePriceInclTax, salesDataCreditmemoItemInterface.basePriceInclTax) &&
        Objects.equals(this.baseRowTotal, salesDataCreditmemoItemInterface.baseRowTotal) &&
        Objects.equals(this.baseRowTotalInclTax, salesDataCreditmemoItemInterface.baseRowTotalInclTax) &&
        Objects.equals(this.baseTaxAmount, salesDataCreditmemoItemInterface.baseTaxAmount) &&
        Objects.equals(this.baseWeeeTaxAppliedAmount, salesDataCreditmemoItemInterface.baseWeeeTaxAppliedAmount) &&
        Objects.equals(this.baseWeeeTaxAppliedRowAmnt, salesDataCreditmemoItemInterface.baseWeeeTaxAppliedRowAmnt) &&
        Objects.equals(this.baseWeeeTaxDisposition, salesDataCreditmemoItemInterface.baseWeeeTaxDisposition) &&
        Objects.equals(this.baseWeeeTaxRowDisposition, salesDataCreditmemoItemInterface.baseWeeeTaxRowDisposition) &&
        Objects.equals(this.description, salesDataCreditmemoItemInterface.description) &&
        Objects.equals(this.discountAmount, salesDataCreditmemoItemInterface.discountAmount) &&
        Objects.equals(this.entityId, salesDataCreditmemoItemInterface.entityId) &&
        Objects.equals(this.discountTaxCompensationAmount, salesDataCreditmemoItemInterface.discountTaxCompensationAmount) &&
        Objects.equals(this.name, salesDataCreditmemoItemInterface.name) &&
        Objects.equals(this.orderItemId, salesDataCreditmemoItemInterface.orderItemId) &&
        Objects.equals(this.parentId, salesDataCreditmemoItemInterface.parentId) &&
        Objects.equals(this.price, salesDataCreditmemoItemInterface.price) &&
        Objects.equals(this.priceInclTax, salesDataCreditmemoItemInterface.priceInclTax) &&
        Objects.equals(this.productId, salesDataCreditmemoItemInterface.productId) &&
        Objects.equals(this.qty, salesDataCreditmemoItemInterface.qty) &&
        Objects.equals(this.rowTotal, salesDataCreditmemoItemInterface.rowTotal) &&
        Objects.equals(this.rowTotalInclTax, salesDataCreditmemoItemInterface.rowTotalInclTax) &&
        Objects.equals(this.sku, salesDataCreditmemoItemInterface.sku) &&
        Objects.equals(this.taxAmount, salesDataCreditmemoItemInterface.taxAmount) &&
        Objects.equals(this.weeeTaxApplied, salesDataCreditmemoItemInterface.weeeTaxApplied) &&
        Objects.equals(this.weeeTaxAppliedAmount, salesDataCreditmemoItemInterface.weeeTaxAppliedAmount) &&
        Objects.equals(this.weeeTaxAppliedRowAmount, salesDataCreditmemoItemInterface.weeeTaxAppliedRowAmount) &&
        Objects.equals(this.weeeTaxDisposition, salesDataCreditmemoItemInterface.weeeTaxDisposition) &&
        Objects.equals(this.weeeTaxRowDisposition, salesDataCreditmemoItemInterface.weeeTaxRowDisposition) &&
        Objects.equals(this.extensionAttributes, salesDataCreditmemoItemInterface.extensionAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalData, baseCost, baseDiscountAmount, baseDiscountTaxCompensationAmount, basePrice, basePriceInclTax, baseRowTotal, baseRowTotalInclTax, baseTaxAmount, baseWeeeTaxAppliedAmount, baseWeeeTaxAppliedRowAmnt, baseWeeeTaxDisposition, baseWeeeTaxRowDisposition, description, discountAmount, entityId, discountTaxCompensationAmount, name, orderItemId, parentId, price, priceInclTax, productId, qty, rowTotal, rowTotalInclTax, sku, taxAmount, weeeTaxApplied, weeeTaxAppliedAmount, weeeTaxAppliedRowAmount, weeeTaxDisposition, weeeTaxRowDisposition, extensionAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalesDataCreditmemoItemInterface {\n");
    sb.append("    additionalData: ").append(toIndentedString(additionalData)).append("\n");
    sb.append("    baseCost: ").append(toIndentedString(baseCost)).append("\n");
    sb.append("    baseDiscountAmount: ").append(toIndentedString(baseDiscountAmount)).append("\n");
    sb.append("    baseDiscountTaxCompensationAmount: ").append(toIndentedString(baseDiscountTaxCompensationAmount)).append("\n");
    sb.append("    basePrice: ").append(toIndentedString(basePrice)).append("\n");
    sb.append("    basePriceInclTax: ").append(toIndentedString(basePriceInclTax)).append("\n");
    sb.append("    baseRowTotal: ").append(toIndentedString(baseRowTotal)).append("\n");
    sb.append("    baseRowTotalInclTax: ").append(toIndentedString(baseRowTotalInclTax)).append("\n");
    sb.append("    baseTaxAmount: ").append(toIndentedString(baseTaxAmount)).append("\n");
    sb.append("    baseWeeeTaxAppliedAmount: ").append(toIndentedString(baseWeeeTaxAppliedAmount)).append("\n");
    sb.append("    baseWeeeTaxAppliedRowAmnt: ").append(toIndentedString(baseWeeeTaxAppliedRowAmnt)).append("\n");
    sb.append("    baseWeeeTaxDisposition: ").append(toIndentedString(baseWeeeTaxDisposition)).append("\n");
    sb.append("    baseWeeeTaxRowDisposition: ").append(toIndentedString(baseWeeeTaxRowDisposition)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    discountAmount: ").append(toIndentedString(discountAmount)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    discountTaxCompensationAmount: ").append(toIndentedString(discountTaxCompensationAmount)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    orderItemId: ").append(toIndentedString(orderItemId)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceInclTax: ").append(toIndentedString(priceInclTax)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    qty: ").append(toIndentedString(qty)).append("\n");
    sb.append("    rowTotal: ").append(toIndentedString(rowTotal)).append("\n");
    sb.append("    rowTotalInclTax: ").append(toIndentedString(rowTotalInclTax)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    taxAmount: ").append(toIndentedString(taxAmount)).append("\n");
    sb.append("    weeeTaxApplied: ").append(toIndentedString(weeeTaxApplied)).append("\n");
    sb.append("    weeeTaxAppliedAmount: ").append(toIndentedString(weeeTaxAppliedAmount)).append("\n");
    sb.append("    weeeTaxAppliedRowAmount: ").append(toIndentedString(weeeTaxAppliedRowAmount)).append("\n");
    sb.append("    weeeTaxDisposition: ").append(toIndentedString(weeeTaxDisposition)).append("\n");
    sb.append("    weeeTaxRowDisposition: ").append(toIndentedString(weeeTaxRowDisposition)).append("\n");
    sb.append("    extensionAttributes: ").append(toIndentedString(extensionAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

