/*
 * Commerce Admin REST endpoints - All inclusive
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.4.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.daill.model.magento;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;


import java.util.ArrayList;
import java.util.List;

/**
 * Interface OrderTaxDetailsItemInterface
 */

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-10-05T21:04:04.031930900+02:00[Europe/Berlin]")
public class TaxDataOrderTaxDetailsItemInterface {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_ITEM_ID = "item_id";
  @SerializedName(SERIALIZED_NAME_ITEM_ID)
  private Integer itemId;

  public static final String SERIALIZED_NAME_ASSOCIATED_ITEM_ID = "associated_item_id";
  @SerializedName(SERIALIZED_NAME_ASSOCIATED_ITEM_ID)
  private Integer associatedItemId;

  public static final String SERIALIZED_NAME_APPLIED_TAXES = "applied_taxes";
  @SerializedName(SERIALIZED_NAME_APPLIED_TAXES)
  private List<TaxDataOrderTaxDetailsAppliedTaxInterface> appliedTaxes = null;

  public static final String SERIALIZED_NAME_EXTENSION_ATTRIBUTES = "extension_attributes";
  @SerializedName(SERIALIZED_NAME_EXTENSION_ATTRIBUTES)
  private Object extensionAttributes;


  public TaxDataOrderTaxDetailsItemInterface type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type (shipping, product, weee, gift wrapping, etc)
   * @return type
  **/
  
  

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public TaxDataOrderTaxDetailsItemInterface itemId(Integer itemId) {
    
    this.itemId = itemId;
    return this;
  }

   /**
   * Item id if this item is a product
   * @return itemId
  **/
  
  

  public Integer getItemId() {
    return itemId;
  }


  public void setItemId(Integer itemId) {
    this.itemId = itemId;
  }


  public TaxDataOrderTaxDetailsItemInterface associatedItemId(Integer associatedItemId) {
    
    this.associatedItemId = associatedItemId;
    return this;
  }

   /**
   * Associated item id if this item is associated with another item, null otherwise
   * @return associatedItemId
  **/
  
  

  public Integer getAssociatedItemId() {
    return associatedItemId;
  }


  public void setAssociatedItemId(Integer associatedItemId) {
    this.associatedItemId = associatedItemId;
  }


  public TaxDataOrderTaxDetailsItemInterface appliedTaxes(List<TaxDataOrderTaxDetailsAppliedTaxInterface> appliedTaxes) {
    
    this.appliedTaxes = appliedTaxes;
    return this;
  }

  public TaxDataOrderTaxDetailsItemInterface addAppliedTaxesItem(TaxDataOrderTaxDetailsAppliedTaxInterface appliedTaxesItem) {
    if (this.appliedTaxes == null) {
      this.appliedTaxes = new ArrayList<TaxDataOrderTaxDetailsAppliedTaxInterface>();
    }
    this.appliedTaxes.add(appliedTaxesItem);
    return this;
  }

   /**
   * Applied taxes
   * @return appliedTaxes
  **/
  
  

  public List<TaxDataOrderTaxDetailsAppliedTaxInterface> getAppliedTaxes() {
    return appliedTaxes;
  }


  public void setAppliedTaxes(List<TaxDataOrderTaxDetailsAppliedTaxInterface> appliedTaxes) {
    this.appliedTaxes = appliedTaxes;
  }


  public TaxDataOrderTaxDetailsItemInterface extensionAttributes(Object extensionAttributes) {
    
    this.extensionAttributes = extensionAttributes;
    return this;
  }

   /**
   * ExtensionInterface class for @see \\Magento\\Tax\\Api\\Data\\OrderTaxDetailsItemInterface
   * @return extensionAttributes
  **/
  
  

  public Object getExtensionAttributes() {
    return extensionAttributes;
  }


  public void setExtensionAttributes(Object extensionAttributes) {
    this.extensionAttributes = extensionAttributes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxDataOrderTaxDetailsItemInterface taxDataOrderTaxDetailsItemInterface = (TaxDataOrderTaxDetailsItemInterface) o;
    return Objects.equals(this.type, taxDataOrderTaxDetailsItemInterface.type) &&
        Objects.equals(this.itemId, taxDataOrderTaxDetailsItemInterface.itemId) &&
        Objects.equals(this.associatedItemId, taxDataOrderTaxDetailsItemInterface.associatedItemId) &&
        Objects.equals(this.appliedTaxes, taxDataOrderTaxDetailsItemInterface.appliedTaxes) &&
        Objects.equals(this.extensionAttributes, taxDataOrderTaxDetailsItemInterface.extensionAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, itemId, associatedItemId, appliedTaxes, extensionAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxDataOrderTaxDetailsItemInterface {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    associatedItemId: ").append(toIndentedString(associatedItemId)).append("\n");
    sb.append("    appliedTaxes: ").append(toIndentedString(appliedTaxes)).append("\n");
    sb.append("    extensionAttributes: ").append(toIndentedString(extensionAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

